## Numpy Library

In [93]:
#Bringing data from own-created csv file(in notpad).
import numpy as np
marks=np.genfromtxt("Documents/marks.csv",dtype='int',skip_header=1)
ex_roll_marks=marks[:,1:]
print("marks of students in 3 subjects brought from a csv file:\n",ex_roll_marks)

print(ex_roll_marks[:,0].min())  #minimum marks in physics
print(ex_roll_marks[:,1].min())  #minimum marks in chemistry
print(ex_roll_marks[:,2].max())  #maximum marks in maths
print(ex_roll_marks[:,0].mean()) #mean marks in physics
print(ex_roll_marks[:,0].sum()) 
print(ex_roll_marks.shape)
print(ex_roll_marks.ndim)
print(marks.dtype)

marks of students in 3 subjects brought from a csv file:
 [[ 98  91  88]
 [ 87  90 100]
 [ 96  97  99]
 [ 65  71  72]
 [ 90  81  87]]
65
71
100
87.2
436
(5, 3)
2
int32


In [34]:
#Bringing data from own-created csv file(in notpad).
import numpy as np
marks=np.loadtxt("Documents/marks.csv",dtype='int',skiprows=1)     
#loadtxt() func doesn't contain skip_header attribute,instead it has skiprows attribute.
print("marks of students in 3 subjects brought from a csv file:\n",marks[:,1:])

marks of students in 3 subjects brought from a csv file:
 [[ 98  91  88]
 [ 87  90 100]
 [ 96  97  99]
 [ 65  71  72]
 [ 90  81  87]]


In [45]:
import numpy as np
filedata=np.genfromtxt("Documents/fdata.csv",dtype=['object','float32','float32','float32','float32'],delimiter=',')
print("File data brought from a csv file:\n",filedata)

File data brought from a csv file:
 [(b'03-10-16', 774.25, 776.065, 769.5 , 772.56)
 (b'04-10-16', 776.03, 778.71 , 772.89, 776.43)
 (b'05-10-16', 779.31, 782.07 , 775.65, 776.47)
 (b'06-10-16', 779.  , 780.48 , 775.54, 776.86)
 (b'07-10-16', 779.66, 779.66 , 770.75, 775.08)]


### Red Wine Data through Numpy

In [127]:
import numpy as np
wine = np.genfromtxt("Documents/winequality-red.csv", delimiter=";", skip_header=1)
print(type(wine))
print("\nWines data:\n",wine)

<class 'numpy.ndarray'>

Wines data:
 [[7.4 0.7 0.0 ... 0.6 9.4 5.0]
 [7.8 0.9 0.0 ... 0.7 9.8 5.0]
 [7.8 0.8 0.0 ... 0.7 9.8 5.0]
 ...
 [6.3 0.5 0.1 ... 0.8 11.0 6.0]
 [5.9 0.6 0.1 ... 0.7 10.2 5.0]
 [6.0 0.3 0.5 ... 0.7 11.0 6.0]]


In [25]:
#Questions:
print("Size of array:",wines.size)
row=len(wines)
col=len(wines[0])
print("No of rows:",row)
print("No of cols:",col)
print("Shape of array:",wines.shape)

print(wines[:,11])      #Quality Column
print(wines[:,11]+2)    #Adding 2 to the quality column

Size of array: 19188
No of rows: 1599
No of cols: 12
Sum: 9012.0
Shape of array: (1599, 12)
[5. 5. 5. ... 6. 5. 6.]
[7. 7. 7. ... 8. 7. 8.]


In [43]:
#See the rows where the quality is b/w 5 and 6.
qual_col=wines[:,11]
res_col=[]
#print(type(res_col))
for val in qual_col:
    if 5<=val<=6:
        res_col.append(val)
        #print(res_col)
print(np.array(res_col))

[5. 5. 5. ... 6. 5. 6.]


In [57]:
#Add row-wise the values and put it in an array.
import numpy as np
from numpy import *
list_sum=[]
for i in range(0,row):
    res=around(wines[i,:].sum(),2)   #around() is present in numpy
    list_sum.append(res)
print(np.array(list_sum))

[ 74.54 123.05  99.7  ... 100.48 105.22  92.49]


In [59]:
#Add rows 1 to 4.
import numpy as np
from numpy import *
list_sum=[]
sum=0
for i in range(0,4):
    res=around(wines[i,:].sum(),2)   #around() is present in numpy
    sum+=res
    list_sum.append(sum)
print(np.array(list_sum))

[ 74.54 197.59 297.29 408.84]


In [128]:
#To see wines which have a quality rating equalto 10.
qual_col=wine[:,11]
res_col=[]
for val in range(len(qual_col)):
    if qual_col[val]==7:
        #np.set_printoptions(formatter={'float_kind':'{:.1f}'.format})
        print("wine:",wine[val,:])
    else:
        pass
print("\nSee only rows 0 to 2:")
print("wine:\n",wine[:3,:])

wine: [7.3 0.7 0.0 1.2 0.1 15.0 21.0 1.0 3.4 0.5 10.0 7.0]
wine: [7.8 0.6 0.0 2.0 0.1 9.0 18.0 1.0 3.4 0.6 9.5 7.0]
wine: [8.5 0.3 0.6 1.8 0.1 35.0 103.0 1.0 3.3 0.8 10.5 7.0]
wine: [8.1 0.4 0.3 2.1 0.1 13.0 30.0 1.0 3.2 0.7 9.7 7.0]
wine: [7.5 0.5 0.2 1.9 0.1 12.0 35.0 1.0 3.4 0.6 9.5 7.0]
wine: [8.0 0.6 0.2 1.8 0.1 3.0 16.0 1.0 3.4 0.9 10.5 7.0]
wine: [5.4 0.8 0.1 1.2 0.0 13.0 93.0 1.0 3.6 0.8 13.0 7.0]
wine: [9.6 0.3 0.5 1.4 0.1 9.0 24.0 1.0 3.2 0.8 10.3 7.0]
wine: [12.8 0.3 0.7 2.6 0.1 9.0 28.0 1.0 3.2 0.8 10.8 7.0]
wine: [12.8 0.3 0.7 2.6 0.1 9.0 28.0 1.0 3.2 0.8 10.8 7.0]
wine: [11.0 0.3 0.6 2.1 0.1 7.0 19.0 1.0 3.3 0.9 10.5 7.0]
wine: [5.2 0.5 0.0 1.6 0.1 19.0 106.0 1.0 3.5 0.6 12.2 7.0]
wine: [15.0 0.2 0.4 2.2 0.1 10.0 24.0 1.0 3.1 0.8 9.2 7.0]
wine: [15.0 0.2 0.4 2.2 0.1 10.0 24.0 1.0 3.1 0.8 9.2 7.0]
wine: [10.0 0.3 0.5 2.6 0.1 14.0 33.0 1.0 3.4 0.8 10.5 7.0]
wine: [11.8 0.3 0.5 1.8 0.1 6.0 10.0 1.0 3.2 0.7 10.2 7.0]
wine: [8.9 0.4 0.3 5.6 0.1 10.0 47.0 1.0 3.4 0.8 10.5 7.0]


In [92]:
qual=wines[:,11]
print("Sum:",qual.sum())   #sum of the quality column
print("Average without using axis:",round(average(qual),2))  #Average without using axis

Sum: 9012.0
Average without using axis: 5.64
[74.5 123.1 99.7 ... 100.5 105.2 92.5]


In [112]:
#Amount of residual sugar present in 4th sample of wine.
wines[3,3]  

1.9

In [117]:
#Amount of citric acid in first three samples of wine.
wines[[0,1,2],2]

array([0.0, 0.0, 0.0])

In [118]:
#Amount of chloride present in all samples.
wines[:,4]

array([0.1, 0.1, 0.1, ..., 0.1, 0.1, 0.1])

In [119]:
#Check the value of all properties corresponding to 5th sample.
wines[4,:]

array([7.4, 0.7, 0.0, 1.9, 0.1, 11.0, 34.0, 1.0, 3.5, 0.6, 9.4, 5.0])

In [120]:
#Check the volatile acidity in all samples.
wines[:,1]

array([0.7, 0.9, 0.8, ..., 0.5, 0.6, 0.3])

In [126]:
print(wines.ndim)
res=wines[2,:]
print(res)
print(res.ndim)
res[4]

2
[7.8 0.8 0.0 2.3 0.1 15.0 54.0 1.0 3.3 0.7 9.8 5.0]
1


0.092

## Reading Red Wine data through Pandas

In [99]:
import pandas as pd
df=pd.read_csv("Documents/winequality-red.csv")
df

fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                                                     
1      7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5                                                                                                                     
2     7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;...                                                                                                                     
3     11.2;0.28;0.56;1.9;0.075;17;60;0.998;3.16;0.58...                                                                                                                     
4      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                                                     
5     7.4;0.66;0;1.8;0.075;13;40;0.9978;3.51;0.56;9.4;5                                                                                                                     
6     7.9;0.6;0.06;1.6;0.069;15;59;0.9964;3.3;0.46;9...                                                                                                                     
7      7.3;0.65;0;1.2;0.065;15;21;0.9946;3.39;0.47;10;7                                                                                                                     
8     7.8;0.58;0.02;2;0.073;9;18;0.9968;3.36;0.57;9.5;7                                                                                                                     
9     7.5;0.5;0.36;6.1;0.071;17;102;0.9978;3.35;0.8;...                                                                                                                     
10    6.7;0.58;0.08;1.8;0.097;15;65;0.9959;3.28;0.54...                                                                                                                     
11    7.5;0.5;0.36;6.1;0.071;17;102;0.9978;3.35;0.8;...                                                                                                                     
12    5.6;0.615;0;1.6;0.089;16;59;0.9943;3.58;0.52;9...                                                                                                                     
13    7.8;0.61;0.29;1.6;0.114;9;29;0.9974;3.26;1.56;...                                                                                                                     
14    8.9;0.62;0.18;3.8;0.176;52;145;0.9986;3.16;0.8...                                                                                                                     
15    8.9;0.62;0.19;3.9;0.17;51;148;0.9986;3.17;0.93...                                                                                                                     
16    8.5;0.28;0.56;1.8;0.092;35;103;0.9969;3.3;0.75...                                                                                                                     
17    8.1;0.56;0.28;1.7;0.368;16;56;0.9968;3.11;1.28...                                                                                                                     
18     7.4;0.59;0.08;4.4;0.086;6;29;0.9974;3.38;0.5;9;4                                                                                                                     
19    7.9;0.32;0.51;1.8;0.341;17;56;0.9969;3.04;1.08...                                                                                                                     
20    8.9;0.22;0.48;1.8;0.077;29;60;0.9968;3.39;0.53...                                                                                                                     
21    7.6;0.39;0.31;2.3;0.082;23;71;0.9982;3.52;0.65...                                                                                                                     
22    7.9;0.43;0.21;1.6;0.

In [102]:
#df['volatile acidity']

KeyError: 'volatile acidity'