In [ ]:
print("hello")

In [ ]:
a=input()
b=input()
c=int(a)+int(b)
print(c)

In [ ]:
a=eval(input())
b=eval(input())
c=a+b
print(c)

In [ ]:
a=eval(input())
b=eval(input())
c=a+b
print(c)

In [ ]:
a=eval(input())
b=eval(input())
if a>b:
    print("a is greatest")
else:
    print("b is greatest")

In [ ]:
a=int(input())
b=int(input())
print(a // b)
print(a/b)

In [ ]:
#Input the basic pay of an employee and calculate the gross pay as per rules.
bpay=eval(input())  #basic pay
hra=0.2*bpay
if hra>3000:
    hra=3000
    
if bpay<50000:      #DA
    da=0.3*bpay
elif (bpay<60000 and bpay>=50000):
    da=0.4*bpay
else:
    da=0.5*bpay
    
pf=0.8*(bpay+da)     #PF
gpay=bpay+hra+da-pf  #gpay
print(gpay)

In [ ]:
#Enter the shape which may be 'C' for Circle,'R' for rectangle,'T' for triangle.Calculate the area after taking values.
shape=eval(input("Enter Character:"))
if (shape=='C' or shape=='c'):
    rad=eval(input("Enter Radius:"))
    area=3.14*rad*rad
    print(area)
elif (shape=='R' or shape=='r'):
    len=eval(input("Enter Length:"))
    bre=eval(input("Enter Breadth:"))
    area=len*bre
    print(area)
elif (shape=='T' or shape=='t'):
    base=eval(input("Enter Base:"))
    height=eval(input("Enter Height:"))
    area=0.5*base*height
    print(area)

In [ ]:
#Enter the income and calculate the income tax as per rules.
income=eval(input("Enter income:"))
if income<500000:
    print("No Tax")
elif income<1000000:
    tax=0.1*(income-500000)
    print(tax)
elif income<2000000:
    incomee=income-1500000
    tax=0.2*incomee+0.1*(income-incomee)
    print(tax)
elif income<3000000:
    sincome=income-1500000
    gincome=(income-sincome-500000)
    tax=0.2*sincome+0.1*gincome
    print(tax)
else:
    sincome=(income-3500000)
    gincome=(income-sincome-1500000)
    tax=0.3*sincome+0.2*gincome+0.1*

In [ ]:
#Enter marks in java,python and C which are out of 100 each.Calculate the percentage of students and award grades.
python=eval(input("Enter marks in Python out of 100:"))
java=eval(input("Enter marks in Java out of 100:"))
C=eval(input("Enter marks in C out of 100:"))
per=((python+java+C)*100)/300
if per>80:
    print("you got A")
elif (per>60 and per<=80):
    print("you got B")
elif (per>40 and per<=60):
    print("you got C")
else:
    print("Fail")

In [ ]:
one=eval(input("Enter first no."))
two=eval(input("Enter second no."))
three=eval(input("Enter third no."))
four=eval(input("Enter fourth no."))
five=eval(input("Enter fifth no."))


In [ ]:
x=10
print(x)
del x
print(x)

In [ ]:
s="sakshi"
del s[0]

In [ ]:
s1="hello"
s2="hello"
s3="hello"
print(id(s1),id(s2),id(s3))

In [ ]:
#print all odd no's between 0 to 100
for i in range(100):
    if(i%2!=0):
        print(i,end=' ')

In [192]:
#print all prime no's between 0 and 100
num=eval(input())
flag=1
for i in range(2,num):
    if num%i==0:
        flag=0
        i+=1
    else:
        flag=1
if(flag==0):
    print(num,"is prime")
else:
    print(num,"is not prime")
    

4
4 is not prime


In [193]:
#WAP to find prime numbers within a given range
beg=eval(input("Enter start:"))
end=eval(input("Enter end:"))
for num in range(beg,end+1):
    count=0
    for i in range(2,(num//2+1)):
        if(num%i==0):
            count+=1
    if(count==0):
        print(num,end=' ')

Enter start:2
Enter end:13
2 3 5 7 11 13 

In [ ]:
#WAP to find those numbers which are divisible by 7 and multiple of 5
for num in range(1500,2700+1):
    if(num%7==0 and num%5==0):
        print(num,end=' ')

In [ ]:
a=eval(input())
b=eval(input())
print("A") if a>b else print("A==B") if a==b else print("B")

In [ ]:
#Print greatest of three numbers using if else in single line
a=eval(input())
b=eval(input())
c=eval(input())
print("A") if a>c else print("C") if a>b else print("B") if b>c else print("C")

In [ ]:
#Fibonacci Series
a=0
b=1
print(a,end=' ')
print(b,end=' ')
for num in range(2,51):
    c=a+b
    print(c,end=' ')
    a=b
    b=c

In [ ]:
#WAP to print all the numbers from 0 to 6 except 3 and 6
for i in range(0,7):
    if i==3 or i==6:
        continue
    print(i)

In [ ]:
#WAP which iterates the integers from 1 to 50.For multiples of 3 print "Fizz" instead of the number and for the multiples of 5 
#print "Buzz".For numbers which are multiples of both 3 and 5 print "FizzBuzz"
for i in range(1,51):
    i=int(input())
    if i%3==0 and i%5!=0:
        print("Fizz")
    elif i%5==0 and i%3!=0:
        print("Buzz")
    elif i%3==0 and i%5==0:
        print("FizzBuzz")

In [ ]:
#WAP to calculate a dog's age in dog's years.
#for first two years,a dog year is equal to 10.5 human years.
#After that,each dog year equals 4 human years

hage=eval(input("Enter dog's age in human years:"))
dogage=((hage-2)*4)+((hage-(hage-2))*10.5)
print(int(dogage))

In [ ]:
#WAP to convert month name into number of days
month=eval(input("Enter month name:"))
if month=="February" or month=="february":
    year=eval(input("Enter year:"))
    if year%4==0:
        print("29 days")
    elif year%400==0:
        print("print 29 days")
    elif year%100==0:
        print("28 days")
    else:
        print("28 days")
elif month in ("April","June","September","November") or month in ("april","june","september","november"):
    print("30 days")
elif month in ("January","March","May","July","August","October","December") or month in ("january","march","may","july","august","october","december"):
    print("31 days")
else:
    print("Enter valid month")

In [ ]:
#WAP to sum of two given integers.If the sum is between 15 to 20 it will return 20.
num1=int(input("Enter first number:"))
num2=int(input("Enter second number:"))
sum=num1+num2
if sum in range(15,21):
    print("sum is:",20)
else:
    print("sum is:",sum)

In [ ]:
#WAP to print the next day of the given date
year=eval(input("Enter year:"))
mon=eval(input("Enter month:"))
dat=eval(input("Enter date:"))
if year%4==0:                     #Year
    leap_year=True
elif year%400==0:
    leap_year=True
elif year%100==0:
    leap_year=False
else:
    leap_year=False
if mon in (1,3,5,7,8,10,12):       #Month
    month_length=31
elif mon==2:          
    if leap_year:
        month_length=29
    else:
        month_length=28
else:
    month_length=30
if dat<month_length:                 #date
    dat=dat+1
else:
    dat=1
    if mon==12:
        mon=1
        year=year+1
    else:
        mon=mon+1
print("The next date:",year,mon,dat)

In [ ]:
a=int(input("a:"))
b=int(input("b:"))
if a>b:
    print("a is greater",str(a))
else:
    print("b is greater",str(b))

In [ ]:
for i in range(500,400,-5):   #reverse order
    print(i,end=' ')

In [ ]:
s='durga'
s*10    #  * is repetitive operator

In [ ]:
complex(10,"10")

In [ ]:
v1="Hyd"
v2="Hyd"
v3="Hyd"
print(id(v1))
print(id(v2))
print(id(v3))
v3='warangle'
print(v3)
print(v2)

In [ ]:
width=17
height=12.0
delimiter='.'

print(width/2)
print(width/2.0)
print(height/3)
print(1+2*5)
print(delimiter*5)

In [ ]:
rad=5
print((4*3.14*5*5*5)/3)   #Volume of sphere

In [ ]:
#WAP to count the number of even and odd numbers from a series of numbers
numbers=(1,2,3,4,5,6,7,8,9)
count_odd=0
count_even=0
for x in numbers:
    if x%2==0:
        count_even+=1
    else:
        count_odd+=1
print("Number of odd numbers:",count_odd)
print("Number of even numbers:",count_even)

In [ ]:
#WAP to find factorial of a number
number=int(input("Enter a number:"))
fact=1
for i in range(1,number+1):
    fact=fact*i
print(fact)

In [ ]:
a=33
b=200
if b>a:
    pass  
#if statement cant be empty,but if you for some reason have an if statement with no content,
#put in the pass statement to avoid getting an error

In [ ]:
#WAP to check whether a number is perfect number or not
num=int(input("Enter a number:"))
sum=0
for i in range(1,num):
    if num%i==0:
        sum+=i
#print(num)
#print(sum)
if num==sum:
    print(num,'is a perfect number')
else:
    print(num,'is not a perfect number')

In [ ]:
#WAP to check whether a number is armstrong or not.
num=int(input("Enter a number:"))
q=num
count=0
summ=0
mult=1
while num!=0:
    count+=1
    num=num//10
#print(count,"count")
#print(q,"q")
r=q
while q!=0:
    rem=q%10
    summ=summ+rem**count   # ** is power operator
    q=q//10
if r==summ:
    print(r,'is armstrong')
else:
    print(r,'is not armstrong')

In [ ]:
#WAP to find the sum of first n natural numbers.
n=int(input("Enter a number:"))
sum1=0
for i in range(1,n+1):
    sum1=sum1+i**2
print(sum1," is the sum of squares of first",n,"natural numbers")

In [ ]:
#WAP to find the ascii value of the character entered.
symb=eval(input("Enter a character:"))
print(ord(symb))  
# ord() function converts the given string of length 'one' into an integer representing the unicode code point of character

In [ ]:
#Simple Method to use Ternary Operator in Python
a,b=10,20
min=a if a<b else b
print(min)

In [ ]:
#WAP to find the reverse of a number
num=int(input("Enter a number"))
rev=0
while num!=0:
    rem=num%10
    rev=rev*10+rem
    num=num//10
print(rev,"is the reverse of the number")

In [ ]:
#WAP to find the sum of first and last digit of the number entered
num=int(input("Enter a number:"))
q=num
last_digit=q%10
while num>9:   # or num<10
    num=num//10
first_digit=num
print(first_digit+last_digit,'is the sum of first and last digit')

In [ ]:
print(223//100)

In [ ]:
#WAP to print even no's upto user's choice range
n=int(input("Enter number:"))
for i in range(1,n+1):
    if i%2==0:
        print(i,end=' ')

In [ ]:
#WAP to print 1,4,9,16,25,......
n=int(input("Enter number:"))
for i in range(1,n+1):
    print(i**2,end=',')

In [ ]:
#WAP to print 1,10,100,1000,10000,.....
n=int(input("Enter number:"))
mul=1
print(mul,end=',')
for i in range(1,n):
    mul=mul*10
    print(mul,end=',')

In [ ]:
#WAP to enter a number and find sum of even digits and product of odd digits
num=int(input("Enter a number:"))
sum2,mul2=0,1
while num!=0:
    rem=num%10
    if(rem%2==0):
        sum2=sum2+rem
    else:
        mul2=mul2*rem
    num=num//10
print(sum2,"is the sum")
print(mul2,"is the product")

In [ ]:
#Retreiving Sub-String
data='From stephen.marquard@uct.ac.za Sat Jan 509:14:16 2008'
atpos=data.find('@')
datpos=data.find('.')
satpos=data.find(' ')
#print(atpos)

sppos=data.find(' ',atpos)  #find space from atpos index
weekpos=data.find(' ',sppos+1)
monpos=data.find(' ',weekpos+1)
datepos=data.find(' ',monpos+1)
yearpos=data.find("'",datepos+1)
#print(datepos)
#print(sppos)

host=data[atpos+1:sppos]
host1=data[datpos+1:sppos]
host2=data[satpos+1:sppos]
host3=data[sppos+1:weekpos]
host4=data[weekpos+1:monpos]
host5=data[monpos+1:datepos]
host6=data[datepos+1:]

print(host)
print(host1)
print(host2)
print(host3)
print(host4)
print(host5)
print(host6)

In [ ]:
#join() function in String
balloon="Sammy has a balloon"
print(" ".join(balloon))
print("*".join(balloon))
print("".join(reversed(balloon)))
print(" ".join(reversed(balloon)))

#split() function in String
print(balloon.split())                   #it returns a list
print(balloon.split('a'))
print(balloon.split('l'))
print(balloon.replace("has","had"))
print(balloon)                          #original string is not changed

In [ ]:
#WAP to reverse a string.
data=eval(input("Enter a String:"))
print(data[::-1])                   #Using slice operator

index=len(data)-1                   #Using while loop
while index>=0:
    letter=data[index]
    print(letter,end='')
    index-=1

print('\n')
for letter in range(0,len(data)):
    print(data[letter],end='')
    
print('\n')

str=" "                             #Using for loop
for i in data:
    str=i+str
print(str)

In [ ]:
#WAP to count the total no of vowels in a string
str1=eval(input("Enter a String:"))
vowel=0
for i in str1:
    if (i=='a' or i=='e' or i=='i' or i=='o' or i=='u'):
        vowel+=1
print("Total no. of vowels are:",vowel)

In [ ]:
#WAP to count the total no of vowels,consonants and spaces in a string
str1=eval(input("Enter a String:"))
vowel=0
consonant=0
spaces=0
digits=0
for i in str1:
    if (i=='a' or i=='e' or i=='i' or i=='o' or i=='u'):
        vowel+=1
    elif(i.isspace()):
        spaces+=1
    elif(i.isdigit()):
        digits+=1
    else:
        consonant+=1
print("Total no. of vowels are:",vowel)
print("Total no. of spaces are:",spaces)
print("Total no. of digits are:",digits)
print("Total no. of consonants are:",consonant)

In [ ]:
#In Python,Updation or deletion of characters from a string is not allowed

#Updation
str2='Original String'
print(str2)
str2[3]='f'
print(str2)

#Deletion
del str2    #Deletion of entire string is possible with the use of del keyword.
print(str2)

In [ ]:
#WAP to check if a substring is present in a string or not.
str1=eval(input("Enter a String:"))
str2=eval(input("Enter a sub-string:"))
if str2 in str1:                                #in is a membership operator
    print("Substring is present in the String")
else:
        print("Substring is not present in the String")

In [ ]:
# title() method in Strings is used to convert each first character of the word to Uppercase
str1='phoebe and mike'
str2=str1.title()
print(str2)

In [ ]:
#Replace all occurences of 'a' with 's'
inp=input("Enter a string:")
print(inp.replace('a','s'))

In [ ]:
take=input("Enter a string:")
lst1=list(take)       #Type Caste
lst2=take.split()
print(lst1)
print(lst2)

In [4]:
#WAP to replace immediate occurence of some letter with '?'.
inpp=input("Enter a string:")
lst=list(inpp)                #String is converted to List because Strings are immutable
for i in range(len(lst)-1):
    if lst[i]==lst[i+1]:
        lst[i+1]='?'
print(lst)
print("".join(lst))          #join() function is used to convert List to String

Enter a string:school
['s', 'c', 'h', 'o', '?', 'l']
scho?l


In [ ]:
#WAP to fetch string after the colon.
str='X-DSPAM-Confidence:0.8475'
atpos=str.find(':')
host=str[atpos+1:]
print(host)

In [1]:
#Input a string and swap the first and last character of the string.
inp=input("Enter a String:")
lisp=list(inp)
#print(lisp)
for i in range(len(lisp)):
    temp=lisp[0]
    lisp[0]=lisp[-1]
    lisp[-1]=temp
print("".join(lisp))

Enter a String:hello world
dello worlh


In [11]:
#Ask user to enter a String and a index,then remove the character present at that index and print the String.
inp=input("Enter a String:")
indexx=int(input("Enter index:"))
#new_str=inp.replace('h','')
new_str=inp[:indexx]+inp[indexx+1:]
print(new_str)

Enter a String:hello
Enter index:5
hello


In [14]:
#Input a Transaction Log and calculate the Net Amount.
while input("Enter q to quit or any other key to continue:")!='q':
    dep=eval(input("Enter Deposit:"))
    witd=eval(input("Enter withdraw:"))
    amnt=dep-witd
    print(amnt)

Enter q to quit or any other key to continue:y
Enter Deposit12000
Enter withdraw4000
8000
Enter q to quit or any other key to continue:q


In [ ]:
#Pattern 1
n=int(input("Enter value of n:"))
for i in range(1,n+1):
    for j in range(1,n+1):
        print('*',end='')
    print('\n')

In [ ]:
#Pattern 2
n=int(input("Enter value of n:"))
for i in range(1,n+1):
    for j in range(1,i+1):  #j<=i
        print('*',end='')
    print('\n')

In [ ]:
#Pattern 3
n=int(input("Enter value of n:"))
for i in range(1,n+1):
    for j in range(1,(n+1-i)+1):   #j<=(n-i)
        print('*',end='')
    print('\n')

In [ ]:
#Pattern 4
n=int(input("Enter value of n:"))
for i in range(1,n+1):
    for j in range(1,(n+1-i)+1,-1):
        print('*',end='')
    print('\n')   
    
    #doubt

In [ ]:
#Pattern 5
for i in range(1,6):
    for j in range(1,10):
        if(j>=6-i and j<=4+i):
            print('*',end='')
    print('\n')

In [1]:
#Pattern 6
for i in range(1,6):
    chr1=65
    for j in range(1,i+1):
        print(chr(chr1),end='')
        chr1+=1
    print()

A
AB
ABC
ABCD
ABCDE


In [21]:
#Pattern 7
string=input("Enter the String:")
length=len(string)
for i in range(0,length):
    for j in range(0,i+1):
        print(string[j],end='')
    print()

Enter the String:sakshi
s
sa
sak
saks
saksh
sakshi


In [12]:
#WAP to add elements in the list
size=eval(input("Enter the size of list:"))
L=[]
s=0
for i in range(0,size):
    a=int(input("Enter element:"))
    L.append(a)
    s=s+L[i]
print(L)
print(s)                 #Total sum of the elements

Enter the size of list:5
Enter element:1
1
Enter element:2
2
Enter element:3
3
Enter element:4
4
Enter element:5
5
[1, 2, 3, 4, 5]
15


In [21]:
#extend() appends one list to another
L1=[2,4,6]
L2=[1,3,5]
L1.extend(L2)
print(L1)
L1.append(9)
L1.append(['a',30])
#L1.append('a',30)
print(L1)
L3=L1+L2      #Using concatenation opertor
print(L3)
print(L1[7][0])
print(L1[7][1])

[2, 4, 6, 1, 3, 5]
[2, 4, 6, 1, 3, 5, 9, ['a', 30]]
[2, 4, 6, 1, 3, 5, 9, ['a', 30], 1, 3, 5]
a
30


In [23]:
#Merge Sort
L1=[5,9,2,3,16]
L2=[10,7,21,6,4]
L1.extend(L2)
print("List before sorting:",L1)
for i in range(len(L1)):
    for j in range(len(L1)-1):
        if(L1[j]>L1[j+1]):
            L1[j],L1[j+1]=L1[j+1],L1[j]
print("List after sorting:",L1)

List before sorting: [5, 9, 2, 3, 16, 10, 7, 21, 6, 4]
List after sorting: [2, 3, 4, 5, 6, 7, 9, 10, 16, 21]


In [24]:
#Ask user to enter a number and check the occurences of the number in the list.
num=int(input("Enter a number:"))
L=[1,6,9,0,3,2,5]
count=0
for i in L:
    if i==num:
        count+=1
print(count)

Enter a number:6
1


In [28]:
L4=[6,3,1,12,4,9]
L4.pop()      #pop() function by default pops the last element
L4.pop(2)     #pop the number at index 2
print(L4)
print(L4.index(3))

[6, 3, 12, 4]
1


In [30]:
#To convert List to Set
L=[6,3,5,6,7,3,1,0,9,3]
myset=set(L)
print("set:",myset)

set: {0, 1, 3, 5, 6, 7, 9}


In [37]:
#Check if the list contains equal number of even and odd numbers.If equal,print True otherwise False.
L=[]
even=0
odd=0
for i in L:
    if i%2==0:
        even+=1
    else:
        odd+=1
if even==odd:
    print(True)
elif len(L)==0:
    print("Empty List",True)
else:
    print(False)

True


In [51]:
L=[7,-1,9,-5,0,-4,2,3]
for i in range(len(L)):
    print(L[i])
    if L[i]<0:
        L.remove(L[i])
#print(L)

7
-1
-5
-4
3


IndexError: list index out of range

In [45]:
L=[7,-1,9,-5,0,-4,2,3]
for i in L:
    if i<0:
        L.remove(i)
print(L)

[7, 9, 0, 2, 3]


In [26]:
#zip() function:
Names=['ben','chen','yaqin']
Gender=[0,0,1]
#zip() function is an Iterator
print(zip(Names,Gender))
#set,list and tuple are known as Iterables
print(set(zip(Names,Gender)))
print(list(zip(Names,Gender)))
print(tuple(zip(Names,Gender)))

{('chen', 0), ('yaqin', 1), ('ben', 0)}
[('ben', 0), ('chen', 0), ('yaqin', 1)]
(('ben', 0), ('chen', 0), ('yaqin', 1))


In [9]:
#Binary Search
L=[902,17,384,283,143,909]
num=int(input("Enter number to search:"))
L.sort()
print(L)
front=0
end=len(L)-1
while front<=end:
    mid=front+(end-front)//2
    found=False
    if num==L[mid]:
        found=True             #element is always found at mid in binary search
        break
    elif num<L[mid]:
        end=mid-1
    elif num>L[mid]:
        beg=mid+1
if found==True:
    print("Element found at position:",mid+1)

Enter number to search:283
[17, 143, 283, 384, 902, 909]
Element found at position: 3


In [7]:
#Sorting list of tuples based on 2nd number in the tuple.
L=[('A',40),('C',30),('B',50)]
for i in range(len(L)):
    for j in range(len(L)-1):
        if L[j][1]>L[j+1][1]:
            L[j],L[j+1]=L[j+1],L[j]    #The whole Tuple has to be swapped
print(L)

[('C', 30), ('A', 40), ('B', 50)]


In [14]:
#Consider two Lists and check whether atleast one of the element is common 
size1=eval(input("Enter size of List 1:"))
L1=[]
for i in range(0,size1):
    a=int(input("Enter element in list 1:"))
    L1.append(a)
    
size2=eval(input("Enter size of List 2:"))
L2=[]
for i in range(0,size2):
    b=int(input("Enter element in list 2:"))
    L2.append(b)
for i in range(len(L1)):
    for j in range(len(L2)):
        if L1[i]==L2[j]:
            print("Element",L1[i],"found at position:",i)

Enter size of List 1:2
Enter element in list 1:1
Enter element in list 1:2
Enter size of List 2:2
Enter element in list 2:3
Enter element in list 2:2
2 found at position: 1


In [2]:
#Count the total number of elements in the List that lie in a particular range.
size1=eval(input("Enter size of List :"))
L1=[]
for i in range(0,size1):
    a=int(input("Enter element in list :"))
    L1.append(a)
print("Enter Range:")
beg=int(input("beg:"))
end=int(input("end:"))
count=0
for i in L1:
    if i>=beg and i<=end:
        count+=1
print("Total number of elements in the list that lie in this range:",count)

Enter size of List :5
Enter element in list :12
Enter element in list :34
Enter element in list :45
Enter element in list :31
Enter element in list :21
Enter Range:
beg:1
end:25
Total number of elements in the list that lie in this range: 2


In [3]:
#Multiply each element of the list by 2 using List Comprehensions.
size1=eval(input("Enter size of List :"))
L1=[]
for i in range(0,size1):
    a=int(input("Enter element in List :"))
    L1.append(a)
#x=[operation for each x in List]
x=[i*2 for i in L1]                          #List Comprehension
print(x)

Enter size of List :4
Enter element in List :21
Enter element in List :1
Enter element in List :2
Enter element in List :3
[42, 2, 4, 6]


In [4]:
#To calculate cube of the numbers using List Comprehension.
size1=eval(input("Enter size of List :"))
L1=[]
for i in range(0,size1):
    a=int(input("Enter element in List :"))
    L1.append(a)
x=[i**3 for i in L1]
print(x)

Enter size of List :3
Enter element in List :1
Enter element in List :2
Enter element in List :3
[1, 8, 27]


In [6]:
#List Comprehensions
vect1=[2,4,6]
vect2=[4,3,-9]
x=[vect1[i]*vect2[i] for i in range(len(vect1))]
y=[vect1[i]*vect2[j] for i in range(len(vect1)) for j in range(len(vect2))]
print(x)
print(y)

[8, 12, -54]
[8, 6, -18, 16, 12, -36, 24, 18, -54]


In [10]:
#WAP to print the Table of a number.
num=int(input("Enter number:"))
Table=[[num,mul,num*mul] for mul in range(1,11)]
print(Table)

Enter number:4
[[4, 1, 4], [4, 2, 8], [4, 3, 12], [4, 4, 16], [4, 5, 20], [4, 6, 24], [4, 7, 28], [4, 8, 32], [4, 9, 36], [4, 10, 40]]


In [19]:
size1=eval(input("Enter size of List 1:"))
L1=[]
for i in range(0,size1):
    a=int(input("Enter element in List 1:"))
    L1.append(a)
size2=eval(input("Enter size of List 2:"))
L2=[]
for i in range(0,size2):
    b=int(input("Enter element in List 2:"))
    L2.append(b)
x=[[L1[i],L2[i]] for i in range(len(L1)) if len(L1)==len(L2)]
print(x)

Enter size of List 1:3
Enter element in List 1:1
Enter element in List 1:2
Enter element in List 1:3
Enter size of List 2:3
Enter element in List 2:4
Enter element in List 2:5
Enter element in List 2:6
[[1, 4], [2, 5], [3, 6]]


In [23]:
#WAP to print those words from the string in a list whose length is greater than or equal to 4.
L1=[]
String='Hello,this,is,very,interesting'
lisp=String.split(',')
for i in lisp:
    if len(i)>=4:
        L1.append(i)
print(L1)

['Hello', 'this', 'very', 'interesting']


In [52]:
#WAP and try to search for a list in another list.
size1=eval(input("Enter size of List 1:"))
L1=[]
for i in range(0,size1):
    a=int(input("Enter element in List 1:"))
    L1.append(a)
size2=eval(input("Enter size of List 2:"))
L2=[]
for i in range(0,size2):
    b=int(input("Enter element in List 2:"))
    L2.append(b)
count=0
if len(L1)==0:
    print("List 1 is empty")
elif len(L2)==0:
    print("List 2 is empty")
else:
    if len(L1)>len(L2):
        for i in L1:
            for j in L2:
                if i==j:
                    count+=1
    elif len(L1)<len(L2):
        for i in L2:
            for j in L1:
                if i==j:
                    count+=1
    if count==len(L2):
        print("Sub-list found in List 1")
    elif count==len(L1):
        print("Sub-list found in List 2")
    else:
        print("Sub-list not found")

Enter size of List 1:4
Enter element in List 1:90
Enter element in List 1:60
Enter element in List 1:78
Enter element in List 1:31
Enter size of List 2:3
Enter element in List 2:14
Enter element in List 2:14
Enter element in List 2:14
Sub-list not found


In [1]:
#WAP to perform Selection Sort
size=eval(input("Enter size of List:"))
L=[]
for i in range(0,size):
    a=int(input("Enter element in List:"))
    L.append(a)
for i in range(len(L)):
    minn=L[i]              #To set new value of min after each iteration
    for j in range(i+1,len(L)):
        if minn>L[j]:
            minn=L[j]
            inn=L.index(minn)
    temp=L[i]
    L[i]=minn
    L[inn]=temp
print(L)

Enter size of List:4
Enter element in List:1
Enter element in List:5
Enter element in List:3
Enter element in List:7


NameError: name 'inn' is not defined

In [5]:
#Square each odd number in the list.
size=eval(input("Enter size of List:"))
L=[]
L1=[]
for i in range(0,size):
    a=int(input("Enter element in List:"))
    L.append(a)
print(L)
for i in L:
    if i%2!=0:
        i=i**2
        L1.append(i)
    else:
        L1.append(i)
print(L1)

Enter size of List:5
Enter element in List:1
Enter element in List:5
Enter element in List:8
Enter element in List:3
Enter element in List:2
[1, 5, 8, 3, 2]
[1, 25, 8, 9, 2]


In [9]:
#Use List Comprehension to square each odd number in a list.
size=eval(input("Enter size of List:"))
L=[]
for i in range(0,size):
    a=int(input("Enter element in List:"))
    L.append(a)
#print(L)
y=[i**2 if i%2!=0 else i for i in L]
print(y)

Enter size of List:5
Enter element in List:1
Enter element in List:2
Enter element in List:3
Enter element in List:4
Enter element in List:5
[1, 2, 3, 4, 5]
[1, 9, 25]
[1, 2, 9, 4, 25]


In [2]:
#Take a range and create a list of tuple within that range with the first element as the number and 
#the second element as the square of the number.
print("Enter range:")
beg=int(input("beg:"))
end=int(input("end:"))
x=[(i,i**2) for i in range(beg,end+1)]
print(x)

Enter range:
beg:1
end:10
[(1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81), (10, 100)]


In [15]:
#Union of two lists
L1=[]
L2=[]
size1=eval(input("Enter size of List 1:"))
for i in range(0,size1):
    a=int(input("Enter element in List 1:"))
    L1.append(a)
size2=eval(input("Enter size of List 2:"))
for i in range(0,size2):
    b=int(input("Enter element in List 2:"))
    L2.append(b)
for i in range(len(L2)):
    L1.append(L2[i])
print(L1)

Enter size of List 1:2
Enter element in List 1:1
Enter element in List 1:2
Enter size of List 2:2
Enter element in List 2:1
Enter element in List 2:2
[1, 2, 1, 2]


In [5]:
#Intersection of two lists
L1=[]
L2=[]
L3=[]
size1=eval(input("Enter size of List 1:"))
for i in range(0,size1):
    a=int(input("Enter element in List 1:"))
    L1.append(a)
size2=eval(input("Enter size of List 2:"))
for i in range(0,size2):
    b=int(input("Enter element in List 2:"))
    L2.append(b)
for i in L1:
    for j in L2:
        if i==j:
            L3.append(i)
print(L3)

Enter size of List 1:3
Enter element in List 1:1
Enter element in List 1:2
Enter element in List 1:3
Enter size of List 2:3
Enter element in List 2:2
Enter element in List 2:3
Enter element in List 2:4
[2, 3]


In [71]:
#To remove the ith occurence of the given word in list where words can repeat.
string=input("Enter a string:")
word=input("Enter word to remove:")
occur=int(input("Enter index of word to remove:"))
lisp=string.split(" ")
lisp1=[]
print("occur:",occur)
count=0
for i in lisp:
    if i==word:
        count+=1
        if count!=occur:
            lisp1.append(i)   #to append the word whose index has not been matched
    else:
        lisp1.append(i)       #to append other words
print(lisp1)
lisp1.sort()
print(lisp1)

Enter a string:hie sakshi bye abba sakshi
Enter word to remove:sakshi
Enter index of word to remove:2
occur: 2
['hie', 'sakshi', 'bye', 'abba']
['abba', 'bye', 'hie', 'sakshi']


In [81]:
#Strings
#WAP that accepts a comma separated sequence of words as input and prints the unique words in sorted form(alphanumerically).
string=input("Enter a comma-separated string:")
lisp=string.split(",")
unique=set(lisp)
my_list=list(unique)
my_list.sort()
str=" ".join(my_list)
print(str)

Enter a comma-separated string:hie,hie,jello,bye
bye hie jello


In [88]:
#Strings
#WAP to remove the characters which have odd index values of a given string.
string=input("Enter a string:")
new_str=""
for chr in range(len(string)):
    if chr%2!=0:
        new_str+=string[chr]
print(new_str)

Enter a string:sakshi
asi


In [ ]:
#Functions

In [14]:
#Syntax 1:
def sum():
    a=5
    b=6
    print(a+b)
sum()

#Syntax 2:
def sum():
    a=5
    b=6
    return (a+b)
x=sum()
print(x)

#Syntax 3:
def sum():
    a=5
    b=6
    return a,b
y,c=sum()
print(y,c)

#4
def sum1(x,y):
    print(x+y)
sum1(2,3)

11
11
5 6
5


In [19]:
#In Python,calling of function is always done by Call by Reference.
def change_me(mylist):
    mylist.append([1,2,3,4])
    print("Values inside the function:",mylist)
    return
mylist=[10,20,30]
change_me(mylist)
print("Values outside the funcrion:",mylist)

Values inside the function: [10, 20, 30, [1, 2, 3, 4]]
Values outside the funcrion: [10, 20, 30, [1, 2, 3, 4]]


In [22]:
def change_me(mylist):
    mylist=[1,2,3,4]     #Here mylist is a local variable whose scope is within the funcion only.
    print("Values inside the function:",mylist)
    return

mylist=[10,20,30]
change_me(mylist)
print("Values outside the function:",mylist)

Values inside the function: [1, 2, 3, 4]
Values outside the function: [10, 20, 30]


In [21]:
#Write a function to check Perfect Number.
def perfect_no(num):
    sum=0
    for i in range(1,num):
        if num%i==0:
            sum+=i 
    return (sum==num)

no=int(input("Enter a number:"))
x=perfect_no(no)

if x==1:
    print(no,"is perfect number")
else:
    print(no,"is not perfect number")

Enter a number:5
5 is not perfect number


In [33]:
#Prog
a=10
def test(a):
    a=20   #Scope of a is within function test() only
    print(a)
    #bb=30
    return ['hello',1,'bye']
print(a)
#print(bb)
test(a)

10
20


['hello', 1, 'bye']

In [36]:
#Keyword Arguments
def print_info(name,age):
    print("Name:",name)
    print("Age:",age)
    return
#call function print_info()
print_info(age=50,name='sakshi')
print_info(name='sakshi',age=50)
#print_info(age=50)

Name: sakshi
Age: 50
Name: sakshi
Age: 50


In [41]:
#Default Arguments
#All default parameters within the parameter list must appear after all non-default parameters.
def test(a,b=10,c=5):
    print("a:",a)
    print("b:",b)
    print("c:",c)
    return
test(4,50)
print('\n')
test(25,c=24)

a: 4
b: 50
c: 5


a: 25
b: 10
c: 24


In [43]:
#Variable length Arguments
#Variable length argument is represented by asterisk(*) sign.

def print_info(arg1,*vartuple):
    print("Output is:")
    print(arg1)
    for var in vartuple:
        print(var)
    return

#Enter list as per user's choice
size=eval(input("Enter size of List:"))
L=[]
for i in range(0,size):
    a=int(input("Enter element in List:"))
    L.append(a)
    
print_info(1,L)

Enter size of List:4
Enter element in List:1
Enter element in List:7
Enter element in List:3
Enter element in List:8
Output is:
1
[1, 7, 3, 8]


In [48]:
#def print_info(*vartuple1,*vartuple2)    This is invalid
#def printf_info(vartuple1,arg)           This is invalid,*vartuple1 has to be present on right hand side

def print_info(*vartuple1):
    print("Output is:")
    for var1 in vartuple1:
        print(var1)
    return

#Enter lists as per user's choice
size1=eval(input("Enter size of List 1:"))
L1=[]
for i in range(0,size1):
    a=int(input("Enter element in list 1:"))
    L1.append(a)

print_info(L1)

Enter size of List 1:4
Enter element in list 1:1
Enter element in list 1:2
Enter element in list 1:3
Enter element in list 1:4
Output is:
[1, 2, 3, 4]


In [51]:
#varargs parameters

def total(initial=5,*numbers,**keywords):
    count=initial
    for num in numbers:
        count+=num
    for key in keywords:
        count+=keywords[key]
    return count

#call to total
print("Total count:",total(5,1,2,3,Phoebe=1,Joey=2))

Total count: 14


In [53]:
#  def total(**keywords,initial=5)       This is invalid
#  def total(**keywords,**numbers)       This is invalid

def total(*numbers,**keywords):
    count=0
    for num in numbers:
        count+=num
    for key in keywords:
        count+=keywords[key]
    return count

#call to total
print("Total count:",total(5,1,2,3,Phoebe=1,Joey=2))

Total count: 14


In [59]:
def func(**Kw):
    for key,value in Kw.items():    #items() function is used to iterate the key value
        print("key:",key,"\n","value:",value)
#call to func()
func(a='monica',b='chandler')

key: a 
 value: monica
key: b 
 value: chandler


In [133]:
def test_var(farg,**kwargs):
    print("Formal arg:",farg)
    for key in kwargs:
        print("Another keyword arg: %s %s" %(key,kwargs[key]))
        # key:a , value: kwargs[key]=hello
        # key:b , value: kwargs[key]=welcome
        
#call to function test_var
test_var(farg=1,a="hello",b="welcome")                        # a and b are keyworded arguments

Formal arg: 1
Another keyword arg: a hello
Another keyword arg: b welcome


In [102]:
#WAP function to convert a given string to all uppercase if it contains at least 2 uppercase characters in the first 4 characters.
def func(str):
    count=0
    for i in range(len(str)):
        if i<4:
            if str[i]>='A' and str[i]<='Z':
                count+=1
    str1=""
    if count>=2:
        str1=str.upper()
        print(str1)
    else:
        print(str)
string=input("Enter a string:")
func(string)

Enter a string:PhOebe
PHOEBE


In [129]:
#WAP function to get a string made of 4 copies of the last two characters of a specified string(length must be at least 2)
def func(str):
    length=len(str)
    if length>=2:
        str_end=str[3:]
        print(str_end)
        new_str=str_end*4
        print(new_str)
    else:
        print(str)
string=input("Enter a string:")
func(string)

Enter a string:hello
lo
lolololo


In [17]:
str1=input("Enter first string:")
str2=input("Enter second string:")
def anagram(str1,str2):
    #sorted() function always return a List
    str1=sorted(str1)
    str2=sorted(str2)
    #print(str1)
    #print(str2)
    if str1==str2:
        print("Strings are anagram")
    else:
        print("Strings are not anagram")
#call
anagram(str1,str2)

Enter first string:yts
Enter second string:shjw
Strings are not anagram


In [14]:
l1=[1,2,3]
l2=[1,2,3]
if l1==l2:
    print("I'm gonna sleep!")

I'm gonna sleep!


In [127]:
#WAP to insert a string in the middle of a string
def func(str,ins_str):
    lenn=len(str)
    mid=lenn//2
    new_str=str[:mid]+" "+ins_str+" "+str[mid:]
    print("New String:",new_str)
    
str1=input("Enter a string:")
str2=input("Enter 2nd string:")
func(str1,str2)

Enter a string:my name sakshi
Enter 2nd string:is
New String: my name is  sakshi


In [147]:
#Lambda Function

#Function Definition
sum=lambda arg1,arg2:arg1+arg2
mult=lambda arg1,arg2:arg1*arg2
sub=lambda arg1,arg2:arg1-arg2

#Function Call
print("Value of total:",sum(10,20))
print("Value of total:",sum(20,20))
print("Value of total:",mult(20,20))
print("Value of total:",sub(10,20))

Value of total: 30
Value of total: 40
Value of total: 400
Value of total: -10


In [142]:
#filter() Function
seq=[0,1,2,3,5,8,13]
result=filter(lambda x:x%2==0,seq)       #filter(function,sequence)
#print(list(result))
#print(tuple(result))
print(set(result))

{0, 8, 2}


In [149]:
# map() Function: It applies the same function to each element of a sequence.
n=[4,3,2,1]
#print(list(map(lambda x:x**2,n)))
print(tuple(map(lambda x:x**2,n)))      #map(function,sequence)

(16, 9, 4, 1)


In [158]:
#reduce() Function: It applies the same operation to items of a sequence.
from functools import reduce
n=[4,3,2,1]
print(reduce(lambda x,y:x*y,n))        # 2 positional arguments are mentioned here

24


In [164]:
import random
y=random.random()
x=random.randrange(50,100)
print(y)
print(x)

0.9149470453776224
93


In [27]:
#Program to filter a given list whether the values in the list are having length of 6 using lambda
lisp=["fbgfh","dgdfgdfgd"]
res=filter(lambda l:len(l)==5,lisp)
print(type(res))
print(list(res))

<class 'filter'>
['fbgfh']


In [12]:
x=lambda l:True if len(l)==6 else False
x(["fbgfh","dgdfgdfgd"])

False

In [17]:
#Python program to count even,odd numbers in a given array of integers using lambda.
lisp=[1,2,3,4,5,6,7,8]
even=len(list(filter(lambda l: l%2==0,lisp)))
odd=len(list(filter(lambda l: l%2!=0,lisp)))
print("Even:",even)
print("Odd:",odd)

Even: 4
Odd: 4


In [29]:
#Python program to find whether a given string starts with a given character using lambda.
str=input("Enter a string:")
chr=input("Enter a character:")
x=lambda seq,sym:True if chr in str else False
print(x(str,chr))
print(type(x))

Enter a string:hello
Enter a character:h
True
<class 'function'>


In [38]:
#Given a string,find all palindromes using lambda.
print("Enter a list of strings:")
size=int(input("Enter size of List:"))
L=[]
for i in range(0,size):
    a=input("Enter element in List:")
    L.append(a)
    
res=filter(lambda x:x=="".join(reversed(x)),L)
print(list(res))

y=lambda x:x=="".join(reversed(x))
print(y("hello"))

Enter a list of strings:
Enter size of List:2
Enter element in List:er
Enter element in List:rt
[]
False


In [34]:
x="keek"
print(reversed(x))

In [1]:
#Check whether two numbers are prime.If both are prime print sum,if one is prime print divide otherwise multiply.
def check_prime(num):
    count=0
    for i in range(2,(num//2+1)):
        if(num%i==0):
            count+=1
    if(count==0 and num!=1):
        return 1
    else:
        return 0

num1=int(input("Enter first number:"))
num2=int(input("Enter second number:"))

x=check_prime(num1)
y=check_prime(num2)
print("x:",x)
print("y:",y)

if x==1 and y==1:
    print("Sum:",num1+num2)
elif (x==1 and y==0) or (x==0 and y==1):
    print("Divide:",num1//num2)
else:
    print("Multiply:",num1*num2)

Enter first number:3
Enter second number:4
x: 1
y: 0
Divide: 0


In [20]:
#Find the sum of digits of a number.Keep on adding numbers until it becomes a single digit.
def single_digit(num):
    sum=0
    while(num!=0):
        rem=num%10
        num=num//10
        sum+=rem
    q=sum
    if(len(str(q))>1):
        single_digit(q)
    else:
        print("Single digit number:",q)

no=int(input("Enter a number:"))
single_digit(no)

Enter a number:33
Single digit number: 6


In [27]:
#Read numbers from a list and find sum of odd numbers and count of odd numbers in odd list,sum of even number and count of even
#numbers in even list.
size=eval(input("Enter size of List:"))
L=[]
odd_list=[]
even_list=[]
for i in range(0,size):
    a=int(input("Enter element in List:"))
    L.append(a)
sum1=0
sum2=0
for item in L:
    if item%2!=0:
        sum1+=item
        odd_list.append(item)
    else:
        sum2+=item
        even_list.append(item)
        
print("Sum of odd numbers:",sum1)
print("Sum of even numbers:",sum2)
print("Odd Numbers List:",odd_list)
print("Count of odd numbers in list:",len(odd_list))
print("Even Numbers List:",even_list)
print("Count of even numbers in list:",len(even_list))

Enter size of List:5
Enter element in List:1
Enter element in List:2
Enter element in List:3
Enter element in List:4
Enter element in List:5
Sum of odd numbers: 9
Sum of even numbers: 6
Odd Numbers List: [1, 3, 5]
Count of odd numbers in list: 3
Even Numbers List: [2, 4]
Count of even numbers in list: 2


In [28]:
vehicle=['tram','scooter','car']
new_vehicle=vehicle
new_vehicle.append('bus')
print(vehicle)
print(new_vehicle)

['tram', 'scooter', 'car', 'bus']
['tram', 'scooter', 'car', 'bus']


In [6]:
print("Lists should be sorted")
size1=eval(input("Enter size of List 1:"))
L1=[]
for i in range(0,size1):
    a=int(input("Enter element in List 1:"))
    L1.append(a)
size2=eval(input("Enter size of List 2:"))
L2=[]
L3=[]
for i in range(0,size2):
    b=int(input("Enter element in List 2:"))
    L2.append(b)
    
for k in range(len(L1)):
        for j in range(len(L2)):
                if L1[k]>L2[j]:
                    L3.append(L2[j])
                    j+=1
                else:
                    L3.append(L1[k])
                    k+=1
                    break
print(L3+L1[k:]+L2[j:])

Lists should be sorted
Enter size of List 1:5
Enter element in List 1:1
Enter element in List 1:5
Enter element in List 1:6
Enter element in List 1:9
Enter element in List 1:11
Enter size of List 2:5
Enter element in List 2:3
Enter element in List 2:4
Enter element in List 2:7
Enter element in List 2:8
Enter element in List 2:10
[1, 3, 4, 5, 3, 4, 6, 3, 4, 7, 8, 9, 3, 4, 7, 8, 10, 11]


In [10]:
# Python3 code to demonstrate 
# to combine two sorted list  
test_list1 = [1, 5, 6, 9, 11] 
test_list2 = [3, 4, 7, 8, 10] 

print ("The original list 1 is : " + str(test_list1)) 
print ("The original list 2 is : " + str(test_list2)) 

size_1 = len(test_list1) 
size_2 = len(test_list2) 

res = [] 
i, j = 0, 0

while i < size_1 and j < size_2: 
    if test_list1[i] < test_list2[j]: 
        res.append(test_list1[i]) 
        i+=1
    else: 
        res.append(test_list2[j]) 
        j+=1
res = res + test_list1[i:] + test_list2[j:] 
print ("The combined sorted list is : " + str(res)) 


The original list 1 is : [1, 5, 6, 9, 11]
The original list 2 is : [3, 4, 7, 8, 10]
The combined sorted list is : [1, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [ ]:
#Dictionary

In [72]:
#Creating a Dictionary
dict={}
dict1={'monica':1,'chandler':2,'phoebe':3,'joey':4}
dict2={'monica':'chandler','rachel':'ross'}
dict3={'food':{'ham':1,'egg':2}}
#dict4={{'ham':1,'egg':2}:1}

print(dict)
print(dict1)
print(dict2)
print(dict2['monica'])                   #d[key]=value
print(dict3)
print(dict3['food']['egg'])
print(dict1.keys())
print(dict1.values())
print("length of dictionary:",len(dict2))
#print(dict1.has_key('monica'))

{}
{'monica': 1, 'chandler': 2, 'phoebe': 3, 'joey': 4}
{'monica': 'chandler', 'rachel': 'ross'}
chandler
{'food': {'ham': 1, 'egg': 2}}
2
dict_keys(['monica', 'chandler', 'phoebe', 'joey'])
dict_values([1, 2, 3, 4])
length of dictionary: 2


In [69]:
#Iterating through a Dictionary
ab={'Phoebe':'New York','Chandler':'Los Angeles'}

#Method 1:
for name,address in ab.items():
    print('Contact {} at {}'.format(name,address))
    
#Method 2:
for key in ab:
    print(key,":",ab[key])
    
if 'Chandler' in ab:
    print("Key is present")
    
print(ab.get('Phoebe'))           #get() function returns the corresponding value associated with the key.

Contact Phoebe at New York
Contact Chandler at Los Angeles
Phoebe : New York
Chandler : Los Angeles
Key is present
New York


In [66]:
# Input: parrot
# Output: ['p':1,'a':1,'r':2,'o':1,'t':1]
str=input("Enter a string:")
def histogram(str):
    d={}
    for ch in str:
        if ch not in d:    #If character is not already present in dictionary,then assign it a value of 1.
            d[ch]=1        #d[key]=value
        else:
            d[ch]+=1       #If character is already present in dictionary,then increment its frequency.
    print(d)
#call
histogram(str)

Enter a string:hello
{'h': 1, 'e': 1, 'l': 2, 'o': 1}


In [68]:
# Input:  {'p':1,'a':1,'r':2,'o':1,'t':1}
# Output: {1:['p','a','o','t'],2:['r']}
d={'p':1,'a':1,'r':2,'o':1,'t':1}
def invert(d):
    d1={}
    for key in d:
        val=d[key]
        if val not in d1:
            d1[val]=[key]     #[] brackets make it a list
        else:
            d1[val].append(key)
    print(d1)
#call
invert(d)

{1: ['p', 'a', 'o', 't'], 2: ['r']}


In [73]:
#in-built functions
d={'p':1,'a':1,'r':2,'o':1,'t':1}
print(sum(d.values()))      #It returns sum of all the values in dictionary
print(max(d.values()))      #It returns the maximum value
print(min(d.values()))      #It returns the minimum value

6
2
1


In [75]:
#Implementing in-built sum() function 
d1={'p':1,'a':1,'r':2,'o':1,'t':1}
sum=0
for key in d1:
    sum+=d1[key]
print("Total sum of values in dictionary:",sum)

Total sum of values: 6


In [19]:
#Implementing in-built max() function
d1={'p':1,'a':1,'r':2,'o':1,'t':1}
max=0
for key in d1:
    if d1[key]>max:
        max=d1[key]
print("Maximum value in dictionary:",max)

Maximum value in dictionary: 2


In [4]:
#Implementing in-built min() function
d1={'p':1,'a':1,'r':2,'o':1,'t':1}
minn=d1['p']
for key in d1:
    if d1[key]<minn:
        minn=d1[key]
print("Minimum value in dictionary:",minn)

Minimum value in dictionary: 1


In [12]:
#Subtract takes dictionaries d1 and d2 and returns a new dictionary that contains all the keys from d1 that are not in d2.
#All those values associated with that keys are set to None.
d1={'p':1,'a':1,'r':2,'o':1,'t':1}
d2={'o':1,'t':1}

def subtract(d1,d2):
    res={}
    for key in d1:
        if key not in d2:
            res[key]=None       #Value of key is set to None
    print(res)
    
#call
subtract(d1,d2)

{'p': None, 'a': None, 'r': None}


In [21]:
# Creating an empty Dictionary 
Dict = {} 
print("Empty Dictionary: ") 
print(Dict) 

# Adding elements one at a time 
Dict[0] = 'Geeks'
Dict[2] = 'For'
Dict[3] = 1
print("\nDictionary after adding 3 elements: ") 
print(Dict) 

# Adding set of values 
# to a single Key 
Dict['Value_set'] = {2, 3, 4}
print("\nDictionary after adding 3 elements: ") 
print(Dict) 

# Updating existing Key's Value 
Dict[2] = 'Welcome'
print("\nUpdated key value: ") 
print(Dict) 

# Adding Nested Key value to Dictionary 
Dict[5] = {'Nested' :{'1' : 'Life', '2' : 'Geeks'}} 
print("\nAdding a Nested Key: ") 
print(Dict) 


Empty Dictionary: 
{}

Dictionary after adding 3 elements: 
{0: 'Geeks', 2: 'For', 3: 1}

Dictionary after adding 3 elements: 
{0: 'Geeks', 2: 'For', 3: 1, 'Value_set': {2, 3, 4}}

Updated key value: 
{0: 'Geeks', 2: 'Welcome', 3: 1, 'Value_set': {2, 3, 4}}

Adding a Nested Key: 
{0: 'Geeks', 2: 'Welcome', 3: 1, 'Value_set': {2, 3, 4}, 5: {'Nested': {'1': 'Life', '2': 'Geeks'}}}


In [24]:
#Creating a Dictionary 
Dict = {1: 'Geeks', 'name': 'For', 3: 'Geeks'} 

#Accessing an element using get() method 
print("Accessing an element using get:") 
print(Dict.get(3)) 

Accessing an element using get:
Geeks


In [25]:
#To input a string,count the occurences of vowels in the string,then make a dictionary and take vowels as key and their occurence
#as value.
str=input("Enter a string:")
d=dict()
for ch in str:
    if ch=='a' or ch=='e' or ch=='i' or ch=='o' or ch=='u':
        if ch not in d:            #if key is not already made,then set its value to 1
            d[ch]=1
        else:
            d[ch]+=1               #otherwise,increment its value
print(d)

Enter a string:hello this is my string
{'e': 1, 'o': 1, 'i': 3}


In [26]:
#With a given integral number n,WAP to generate a dictionary that contains(i,i*i) such that it is an integral no. b/w i and n
#(both included) and then program should print the dictionary.
num=int(input("Enter a number:"))
d=dict()
for i in range(1,num+1):
    d[i]=i*i
print(d)

Enter a number:4
{1: 1, 2: 4, 3: 9, 4: 16}


In [32]:
num=int(input("Enter a number:"))
d=dict()
for i in range(1,num+1):
    d[i]=round(i**0.5,2)
print(d)

Enter a number:3
{1: 1.0, 2: 1.41, 3: 1.73}


In [31]:
person=dict()
person['children']=['anu','renu','anil']     #key has a value as list
person['pets']={'dog':'dubo','cat':'cutie'}  #key has a value as dictionary

for key,val in person.items():
    if type(val) is list:
        for i in val:
            print(i)
    elif type(val) is dict:
        for k,v in val.items():
            print(k,':',v)

anu
renu
anil
dog : dubo
cat : cutie


In [3]:
#Please write a program to generate all sentences.
Subject=['I','You']
Verb=['Play','Love']
Object=['Hockey','Football']
for s in Subject:
    for v in Verb:
        for o in Object:
            print(s+" "+v+" "+o)

I Play Hockey
I Play Football
I Love Hockey
I Love Football
You Play Hockey
You Play Football
You Love Hockey
You Love Football


In [90]:
#update() function : To add one dictionary in another.
dict1={1:"Moo Point!",2:"Unagi",3:"Break"}
dict2={4:"Monica",5:"I know",6:"Noooo!!!!"}
dict1.update(dict2)
print(dict1)

{1: 'Moo Point!', 2: 'Unagi', 3: 'Break', 4: 'Monica', 5: 'I know', 6: 'Noooo!!!!'}


In [168]:
#fromkeys() function : To transform sequence into dictionary.
seq=['name','age','id']
dict1={}

dict1=dict.fromkeys(seq,5)
print(dict1)
#ss=lambda x: x for x in range(0,3)
dict1=dict1.fromkeys(range(3))
print(dict1)

dict1=dict.fromkeys(seq,seq)
print(dict1)

dict1=dict.fromkeys(seq,lambda:hello)
print(dict1)

dict1=dict.fromkeys(seq,"hello")
print(dict1)

dict1=dict.fromkeys(seq,None)
print(dict1)

{'name': 5, 'age': 5, 'id': 5}
{0: None, 1: None, 2: None}
{'name': ['name', 'age', 'id'], 'age': ['name', 'age', 'id'], 'id': ['name', 'age', 'id']}
{'name': <function <lambda> at 0x00000152CCB7B598>, 'age': <function <lambda> at 0x00000152CCB7B598>, 'id': <function <lambda> at 0x00000152CCB7B598>}
{'name': 'hello', 'age': 'hello', 'id': 'hello'}
{'name': None, 'age': None, 'id': None}


In [76]:
#fromkeys()     Book
k={1,'a',2,'b'}
#print(type(k))

d=dict.fromkeys(k)
print(d)

d1=dict.fromkeys(k,10)
print(d1)

v=[1]                 #A list of values can also be provided as an argument.
d2=dict.fromkeys(k,v)
print(d2)

#dictionary comprehensions
ke={1,2,3}
va=['ab','cd','ef']
d3=dict(zip(ke,va))
print(d3)

{1: None, 2: None, 'b': None, 'a': None}
{1: 10, 2: 10, 'b': 10, 'a': 10}
{1: [1], 2: [1], 'b': [1], 'a': [1]}
{1: 'ab', 2: 'cd', 3: 'ef'}


In [78]:
# Python code to demonstrate dictionary comprehension 

# Lists to represent keys and values 
keys = ['a','b','c','d','e'] 
values = [1,2,3,4,5] 

# Method 1:
#myDict = { k:v for (k,v) in zip(keys, values)} 

# Method 2:
myDict = dict(zip(keys, values)) 

print (myDict) 

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}


In [34]:
d1={}
d2={10,20}
d3={1:2,2:3}
print(type(d1))
print(type(d2))
print(type(d3))

<class 'dict'>
<class 'set'>
<class 'dict'>


In [39]:
#dictionary
b={1:100,2:200,3:300}    
print(b[1])
print(b[2])
print(b[3])
#print(b[4])

#default dictionary
from collections import defaultdict
c=defaultdict(int)
c[1]=100
c[2]=200
c[3]=300
print(c[4])

100
200
300
0


In [42]:
#A dictionary can be constructed from a multiple list of tuples.It uses the dict keyword.
d=dict([("x",50),("y",60)])
print(d)

{'x': 50, 'y': 60}


In [43]:
#In case of duplicate keys,only the last value will be maintained in the dictionary.
q={1:100,1:200}
print(q)

{1: 200}


In [47]:
q1={('key'):100}    #tuple can be taken as a key
print(q1)
#q1={['key']:100}    #list cannot be taken as a key
#print(q1)

{'key': 100}


In [48]:
#The == operator can be used to compare two dictionaries.
d1={1:100,2:200}
d2={1:100,2:200}
print(d1==d2)

True


In [57]:
d1={1:100,2:200}
d1=str(d1)
print(type(d1))
print(len(d1))

#del(d1[1])
#print(d1)

#doubt

2
{2: 200}


In [89]:
#Dictionary Operations
d1={1:"a",2:"b",3:"c",4:"d"}
print(d1.keys())
print(d1.values())
print(d1.clear())
print(d1)

#items()
d3={1:'ab',2:'cd',3:'ef'}
print(d3.items())

dict_keys([1, 2, 3, 4])
dict_values(['a', 'b', 'c', 'd'])
None
{}
dict_items([(1, 'ab'), (2, 'cd'), (3, 'ef')])


In [62]:
#copy() function by default performs Shallow Copy.
d1={1:100,2:"abc",3:"5+9j"}
print("\nd1:",d1)
print("\nType of d1:",type(d1))
d2=d1.copy()
print("\nd2:",d2)
print("\nType of d2:",type(d2))
d1[1]=986
print("\nd1:",d1)
print("\nd2:",d2)


d1: {1: 100, 2: 'abc', 3: '5+9j'}

Type of d1: <class 'dict'>

d2: {1: 100, 2: 'abc', 3: '5+9j'}

Type of d2: <class 'dict'>

d1: {1: 986, 2: 'abc', 3: '5+9j'}

d2: {1: 100, 2: 'abc', 3: '5+9j'}


In [81]:
#get() : It is used to find the input key and return the corresponding value.
d3={1:'ab',2:'cd',3:'ef'}
#print(d3.get())
print(d3.get(1))
print(d3.get(4))

ab
None


In [88]:
#setdefault()
d4={}
d4.setdefault(1,None)
#d4.setdefault(1,'None')
print(d4)

{1: None}


In [99]:
#pop():returns the element from the current dictionary object.
d1={1:10,2:'a',3:55.43,4:'c',5:'d'}
print(d1)
print(d1.pop(3))
print(d1)
#print(d1.pop(10))
print(d1.pop(10,"Key not found"))

{1: 10, 2: 'a', 3: 55.43, 4: 'c', 5: 'd'}
55.43
{1: 10, 2: 'a', 4: 'c', 5: 'd'}
Key not found


In [100]:
#popitem():removes the topmost element from the current dictionary object.
stack={'a':10,'b':20,'c':30}
print("Stack:",stack)
top=stack.popitem()
print("top:",top)
print("Stack after pop:",stack)

Stack: {'a': 10, 'b': 20, 'c': 30}
top: ('c', 30)
Stack after pop: {'a': 10, 'b': 20}


In [103]:
#Dictionary Comprehension
#stack={y*2 for y in range(10)}
stack={y:y*2 for y in range(10)}
print(stack)

{0: 0, 1: 2, 2: 4, 3: 6, 4: 8, 5: 10, 6: 12, 7: 14, 8: 16, 9: 18}


In [104]:
# Python code to demonstrate dictionary creation using list comprehension 
myDict = {x: x**2 for x in [1,2,3,4,5]} 
print (myDict) 

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [107]:
#WAP to read the elements of dictionary from console I/O and display the dictionary.
d={}
n=int(input("Enter the length:"))
for i in range(n):
    k=eval(input("Enter the key:"))
    v=eval(input("Enter the value:"))
    d[k]=v
    #or,
    #x={k:v}
    #d.update(x)
print(d)

Enter the length:1
Enter the key:1
Enter the value:2
{1: 2}


In [112]:
#WAP to check whether or not the user-provided keys are available in the dictionary with 'in' operator.
d={}
n=int(input("Enter the length:"))
for i in range(n):
    k=eval(input("Enter the key:"))
    v=eval(input("Enter the value:"))
    d[k]=v
print(d)

search_key=eval(input("Enter the key to be searched:"))

if search_key in d.keys():
    print("The key is available")
else:
    print("The key is not available")

Enter the length:2
Enter the key:1
Enter the value:2
Enter the key:2
Enter the value:3
{1: 2, 2: 3}
Enter the key to be searched:4
The key is not available


In [113]:
#WAP to print sorted dictionary.
d={1:56,8:90,56:45,2:45}
sorted_d=sorted(d)      #sorted function returns a list.
print("Sorted dictionary:",sorted_d)

Sorted dictionary: [1, 2, 8, 56]


In [122]:
#WAP to check whether the dictionary is empty or not.
d={1:20}
if (d=={}):
    print("Dictionary is empty")
else:
    print("Dictionary is not empty")

Dictionary is not empty


In [123]:
#WAP to remove all the items in the input dictionary.
d={1:56,8:90,56:45,2:45}
d.clear()
print(d)

{}


In [128]:
#d=dict("hai")
print("dictionary:",d)
s=set("hai")
print("set:",s)

dictionary: {}
set: {'i', 'h', 'a'}


In [136]:
#Counter
from collections import Counter

list1=[1,2,3,4,1,2,6,7,3,8,1]
cnt=Counter(list1)           #The counter() function takes an iterable/mapping as argument and returns a dictionary.
print(cnt)
print(cnt[1])

Counter({1: 3, 2: 2, 3: 2, 4: 1, 6: 1, 7: 1, 8: 1})
3


In [167]:
#elements() function of Counter

#list1=[1,2,3,4,1,2,6,7,3,8,1]
d={1:3,2:4}
cnt=Counter(d)
print("Type of counter object:",type(cnt))
print(tuple(cnt.elements()))
print(list(cnt.elements()))

#doubt

Type of counter object: <class 'collections.Counter'>
(1, 1, 1, 2, 2, 2, 2)


In [144]:
# most_common() function: It is applicable on counter object only.
list1=[1,2,3,4,1,2,6,7,3,8,1]
cnt=Counter(list1)
print(cnt.most_common())

[(1, 3), (2, 2), (3, 2), (4, 1), (6, 1), (7, 1), (8, 1)]


In [151]:
# subtract() function
d={1:3,2:4}
cnt=Counter(d)
deduct={1:1,2:2}
cnt.subtract(deduct)
print(cnt)

Counter({1: 2, 2: 2})


In [152]:
#defaultdict
from collections import defaultdict

nums=defaultdict(int)
nums['one']=1
nums['two']=2
print(nums['three'])

0


In [155]:
count=defaultdict(int)
print(type(count))
names_list="Mark John Smith Mark Mark John Hedger Smith John John".split()   #split() function returns a list
print(type(names_list))
for names in names_list:
    count[names]+=1
print(count)

<class 'collections.defaultdict'>
<class 'list'>
defaultdict(<class 'int'>, {'Mark': 3, 'John': 4, 'Smith': 2, 'Hedger': 1})


In [156]:
text=defaultdict(lambda:'hello')
text['a']='Python'
text['b']='Java'
print(text['a'])
print(text['c'])

Python
hello


In [16]:
# Input : city_list=[('Punjab','Jalandhar'),('Punjab','Amritsar'),('Himachal','Shimla'),('Haryana','Delhi'),('Haryana','Hisar')]
# Output: {'Punjab':['Jalandhar','Amritsar'],'Himachal':['Shimla'],'Haryana':['Delhi','Hisar'] }
from collections import defaultdict
city_list=[('Punjab','Jalandhar'),('Punjab','Amritsar'),('Himachal','Shimla'),('Haryana','Delhi'),('Haryana','Hisar')]
d=defaultdict(list)
for k,v in city_list:
    d[k].append(v)
    print("d[k]",d[k])
print(d)

d[k] ['Jalandhar']
d[k] ['Jalandhar', 'Amritsar']
d[k] ['Shimla']
d[k] ['Delhi']
d[k] ['Delhi', 'Hisar']
defaultdict(<class 'list'>, {'Punjab': ['Jalandhar', 'Amritsar'], 'Himachal': ['Shimla'], 'Haryana': ['Delhi', 'Hisar']})


In [15]:
city_list=[('Punjab','Jalandhar'),('Punjab','Amritsar'),('Himachal','Shimla'),('Haryana','Delhi'),('Haryana','Hisar')]
d=dict()
for k,v in city_list:
    if k not in d:
        print("k",k)
        print("v",v)
        d[k]=[v]
    else:
        d[k].append(v)
print("d:",d)

k Punjab
v Jalandhar
k Himachal
v Shimla
k Haryana
v Delhi
d: {'Punjab': ['Jalandhar', 'Amritsar'], 'Himachal': ['Shimla'], 'Haryana': ['Delhi', 'Hisar']}


In [18]:
from collections import defaultdict
d=defaultdict(list)
d['monica'].append('chandler')
d['regina'].append('phalange')
for k,v in d.items():
    print(k,":",v)

monica : ['chandler']
regina : ['phalange']


In [ ]:
#Numpy Library

In [30]:
import numpy as np
from numpy import *

a=array([1,2,3,4])
b=array([1.4,2.4,5.8])
c=array([1.5,1,4.5])
d=array(['a','b','c'])
e=array(['Monica','Rachel','123456789012345'])
print("a:",a)
print("Type of a:",type(a))
print("Data type of array a:",a.dtype)     #32-bit integer
print("Data type of array b:",b.dtype)
print("Data type of array c:",c.dtype)
print("Data type of array d:",d.dtype)
print("Data type of array e:",e.dtype)
print(a.itemsize)
print(e.itemsize)
print(b.itemsize)
print("Number of elements in array a:",a.size)
print("Shape of array a:",a.shape)

a: [1 2 3 4]
Type of a: <class 'numpy.ndarray'>
Data type of array a: int32
Data type of array b: float64
Data type of array c: float64
Data type of array d: <U1
Data type of array e: <U15
4
60
8
Number of elements in array a: 4
Shape of array a: (4,)


In [50]:
a=array([1,2,3,4])
print("a:",a)
print("\na[0]:",a[0])

a.fill(9)
print("\n a.fill(9) :",a)
#or use Slicing
a[:]=2
print("\na[:] :",a)

a[0]=10.4
print("a[0] :",a)
#Slicing is a view,that means the changes done using slicing are permanent.

b=array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[1,3,5,7,9]])
print("\nb:",b)
print("\nb[0,3:4] :",b[0,3:4])
print("\nb[2:,2:] :",b[2:,2:])
print("\nb[:2,:2] :",b[:2,:2])
print("\nb[2:,0] :",b[2:,0])   #doubt
print("\nb[2:,2:] :",b[2:,2:])
print("\nb[-1:,-1:] :",b[-1:,-1:])
print("\nb[-1:,-2:] :",b[-1:,-2:])
print("\nb[-3:,-2:] :",b[-3:,-2:])
print("\nb[-3:,-1:] :",b[-3:,-1:])
print("\nb[-3:,-1:] :",b[-3:,-1:])

a: [1 2 3 4]

a[0]: 1

 a.fill(9) : [9 9 9 9]

a[:] : [2 2 2 2]
a[0] : [10  2  2  2]

b: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [ 1  3  5  7  9]]

b[0,3:4] : [4]

b[2:,2:] : [[13 14 15]
 [ 5  7  9]]

b[:2,:2] : [[1 2]
 [6 7]]

b[2:,0] : [11  1]

b[2:,2:] : [[13 14 15]
 [ 5  7  9]]

b[-1:,-1:] : [[9]]

b[-1:,-2:] : [[7 9]]

b[-3:,-2:] : [[ 9 10]
 [14 15]
 [ 7  9]]

b[-3:,-1:] : [[10]
 [15]
 [ 9]]


In [56]:
#Strides
b=array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[1,3,5,7,9],[4,5,6,7,8]])
print("b:",b)
print("\nb[2::2,::2] :",b[2::2,::2])

print("\nb[0::3,1::3] :",b[0::3,1::3]) 
#Start from row    0 and skip by a factor of 3
#Start from column 1 and skip by a factor of 3

b: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [ 1  3  5  7  9]
 [ 4  5  6  7  8]]

b[2::2,::2] : [[11 13 15]
 [ 4  6  8]]

b[0::3,1::3] : [[2 5]
 [3 9]]


In [117]:
#Quick Method to create Array

# arange(start,stop,step,dtype)
x=arange(4)
print("x:",x)
print("\narange(9) :",arange(9))
b=arange(1,5,2)
print("\nb:",b)
d=arange(2,8,2,float)
print("\nd:",d)

b=arange(12).reshape(4,3)
print("\nb:",b)
#print(b.reshape(5,4))        ValueError: cannot reshape array of size 12 into shape (5,4)
print("\nb.reshape(2,6) :",b.reshape(2,6))



# ones(shape,dtype,order)
y=ones((3,2),float,'F')
print("\ny:",y)
print("\nType of y:",y.dtype)

z=ones((4,3))
print("\nz:",z)
print("\nType of z:",z.dtype)    #default data type is : float64

c=ones((3,3),int)
print("\nc:",c)
print("\nType of c:",c.dtype)


#zeros()
print("\nzeros((5,6)) :",zeros((5,6)))

x: [0 1 2 3]

arange(9) : [0 1 2 3 4 5 6 7 8]

b: [1 3]

d: [2. 4. 6.]

b: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

b.reshape(2,6) : [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

y: [[1. 1.]
 [1. 1.]
 [1. 1.]]

Type of y: float64

z: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Type of z: float64

c: [[1 1 1]
 [1 1 1]
 [1 1 1]]

Type of c: int32

zeros((5,6)) : [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [104]:
# random in numpy
y=np.random.random(3)
print("\ny:",y)
print("Data type of y:",y.dtype)

x=np.random.random_sample((3, 2))     #or   random.random_sample((3,2))
print("\nx:",x)

z=5*np.random.random_sample((3, 2))
print("\nz:",z)


y: [0.04988919 0.50661826 0.22297211]
Data type of y: float64

x: [[0.1984073  0.84980247]
 [0.04524882 0.8637108 ]
 [0.60116914 0.00335781]]

z: [[1.90020842 1.48961468]
 [3.74315804 3.26194956]
 [4.14938898 1.7892396 ]]


In [119]:
x=int(input())
y=int(input())
z=int(input())
n=int(input())
for i in range(x+1):
    for j in range(y+1):
        for k in range(z+1):
            if (i+j+k)!=n:
                print([i,j,k],end='')

1
1
1
2
[0, 0, 0][0, 0, 1][0, 1, 0][1, 0, 0][1, 1, 1]

In [121]:
marks = {}
for i in range(int(input())):
    line = input().split()
    marks[line[0]] = list(map(float, line[1:]))
print('%.2f' %(sum(marks[input()])/3))

1
sakshi 12 12 12
sakshi
12.00


In [3]:
marks={}  #dictionary
for i in range(int(input("Enter no. of students:"))):                          #This loop will run for the total no. of students
    data=input("Enter name of student and marks in 3 subjects in a single line:").split()    #it will return a list
    marks[data[0]]=list(data[1:])                                      #key:name of student  value:list of marks of that student
avg=sum(marks[input()])/3
print(avg)

Enter no. of students:2
Enter name of student and marks in 3 subjects in a single line:sakshi 65 78 90
Enter name of student and marks in 3 subjects in a single line:priya 43 45 67
sakshi


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [16]:
#Converting List to Array in Numpy
import numpy as np
from numpy import *

list1=[1,2,3,4]
#print(list1)
arr=array(list1)       #1-D array
#print("list1 +2 :",list1+2)                  TypeError: can only concatenate list (not "int") to list
print("\nArray corresponding to the list:",arr)
print("arr+2 :",arr+2)
print("arr*2 :",arr*2)
print("arr-2 :",arr-2)

list2=[[1,2],[3,4],[5,6]]
arr2=array(list2)     #2-D array
print("\nArray corresponding to lists of lists:",list2)

list3=[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
      [[11,22,33],[44,55,66],[77,88,99],[100,111,112]]]
arr3=array(list3)
print("\nArray corresponding to lists of lists of list:",arr3)


Array corresponding to the list: [1 2 3 4]
arr+2 : [3 4 5 6]
arr*2 : [2 4 6 8]
arr-2 : [-1  0  1  2]

Array corresponding to lists of lists: [[1, 2], [3, 4], [5, 6]]

Array corresponding to lists of lists of list: [[[  1   2   3]
  [  4   5   6]
  [  7   8   9]
  [ 10  11  12]]

 [[ 11  22  33]
  [ 44  55  66]
  [ 77  88  99]
  [100 111 112]]]


In [27]:
#To convert Array to List
arr1=array([1,2,3,4])
arr2=array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
      [[11,22,33],[44,55,66],[77,88,99],[100,111,112]]])
arr3=array([[1,2],[3,4],[5,6]])
print("Array arr1 :",arr1)
print("List corresponding to array:",arr1.tolist())

print("No of dimensions in array:",arr1.ndim)
print("Shape of array arr1:",arr1.shape)
print("Shape of array arr2:",arr2.shape)
print("Shape of array arr3:",arr3.shape)

Array arr1 : [1 2 3 4]
List corresponding to array: [1, 2, 3, 4]
No of dimensions in array: 1
Shape of array arr1: (4,)
Shape of array arr2: (2, 4, 3)
Shape of array arr3: (3, 2)


In [39]:
#Logical Expressions can be applied on array
arr=array([[1,2],[3,4],[5,6]])
b=arr>4
print("b:",b)               #It will return an array of True and False
print("\narr[b]:",arr[b])   #It will return as O/P those values which returned True in print(b) statement
print("\narr[False] :",arr[False])
print("\narr[True] :",arr[True])

b: [[False False]
 [False False]
 [ True  True]]

arr[b]: [5 6]

arr[False] : []

arr[True] : [[[1 2]
  [3 4]
  [5 6]]]


In [52]:
#nan and inf
arr=array([[1,2],[3,4],[5,6]])
arr[0,1]=nan   #doubt
print(arr)
arr[1,1]=inf
print("\n",arr)  

ValueError: cannot convert float NaN to integer

In [49]:
arr=array([[1,2],[3,4],[5,6]])
print("Column-wise min value:",amin(arr,axis=0))
print("Row-wise min value:",amin(arr,axis=1))
print("Cumulative sum:",cumsum(arr))
print("Flattening:",arr.flatten())

Column-wise min value: [1 2]
Row-wise min value: [1 3 5]
Cumulative sum: [ 1  3  6 10 15 21]
Flattening: [1 2 3 4 5 6]


In [65]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]],dtype='float')       #creating array from list with type float
print("Array using list :",arr)

arr1=np.array((1,2,3))             #creating array from tuple
print("\nArray using tuple :",arr1)

arr2=np.zeros((2,3))
print("\nArray with all zeros :\n",arr2)

arr3=np.full((3,3),5)              #creating a constant array with all same values
print("\narr3:\n",arr3)

arr4=np.full((3,3),4,dtype='complex')
print("\narr4:\n",arr4)

arr5=np.random.random((2,2))
print("\nArray with random values :\n",arr5)

arr6=np.arange(0,30,5)       #creates a sequence of integers from 0 to 30 with step size 5
print("\nArange :",arr6)

arr8=arr7.flatten()                                         #to flatten the array in single list
print("\nFlattened Array :",arr8)

Array using list : [[1. 2. 3.]
 [4. 5. 6.]]

Array using tuple : [1 2 3]

Array with all zeros :
 [[0. 0. 0.]
 [0. 0. 0.]]

arr3:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

arr4:
 [[4.+0.j 4.+0.j 4.+0.j]
 [4.+0.j 4.+0.j 4.+0.j]
 [4.+0.j 4.+0.j 4.+0.j]]

Array with random values :
 [[0.89870997 0.28605566]
 [0.70003711 0.26096149]]

Arange : [ 0  5 10 15 20 25]

Reshaped Array :
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Flattened Array : [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [71]:
#Reshape
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])      #3*4 array
rshape1=arr.reshape(2,3,2)                              #creates 2 arrays of 2*3
rshape2=arr.reshape(2,6)                                #creates 1 array of 2*6
rshape3=arr.reshape(3,2,2)                              #creates 3 arrays of 2*2
print("\nReshaped Array 1 :\n",rshape1)
print("\nReshaped Array 2 :\n",rshape2)
print("\nReshaped Array 3 :\n",rshape3)


Reshaped Array 1 :
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Reshaped Array 2 :
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshaped Array 3 :
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [23]:
arr1=np.array([[1,2],[3,4],[5,6]])
print("arr1:",arr1)

arr2=arr1.copy()
print("\narr2:",arr2)

arr2[0][1]=10
print("\narr1:",arr1)
print("arr2:",arr2)

arr3=arr2[:1,:1].copy()    
print("\narr1:",arr1)
print("arr2:",arr2)

arr1: [[1 2]
 [3 4]
 [5 6]]

arr2: [[1 2]
 [3 4]
 [5 6]]

arr1: [[1 2]
 [3 4]
 [5 6]]
arr2: [[ 1 10]
 [ 3  4]
 [ 5  6]]

arr1: [[1 2]
 [3 4]
 [5 6]]
arr2: [[ 1 10]
 [ 3  4]
 [ 5  6]]


# arr1=[[1,2],[3,4],[5,6]]
print("arr1:",arr1)

arr2=arr1.copy()
print("\narr2:",arr2)
arr3=arr2[:2,:2].copy()


In [2]:
#Unary Operators
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Largest element is :\n",arr1.max())
print("Row wise largest element :\n",arr1.max(axis=1))
print("Column wise largest element :\n",arr1.max(axis=0))

print("Minimum element is :\n",arr1.min())
print("Row wise Minimum element is :\n",arr1.min(axis=1))
print("Column wise Minimum element is :\n",arr1.min(axis=0))

Largest element is :
 9
Row wise largest element :
 [3 6 9]
Column wise largest element :
 [7 8 9]
Minimum element is :
 1
Row wise Minimum element is :
 [1 4 7]
Column wise Minimum element is :
 [1 2 3]


In [5]:
#Fancy indexing in 1-D
C=np.array([123,188,190,99,77,88,100])  #The array C in indexed  by applying a mask(array)
A=np.array([4,7,2,8,6,9,5])  #The Boolean mask of one array is used to select the corresponding elements of other array.
R=C[A<=5]
print("Result :",R)
print(C[[1,2,3]])   

Result : [123 190 100]
[188 190  99]


In [6]:
#fancy indexing in 2-D
arr=np.array([[0,1,2,3,4,5],
            [10,11,12,13,14,15],
            [20,21,22,23,24,25],
            [30,31,32,33,34,35],
            [40,41,42,43,44,45],
            [50,51,52,53,54,55]])

#accessing one to one mapping, 0,1    1,2   2,3   3,4   4,5 

a=arr[(0,1,2,3,4),(1,2,3,4,5)]
print("Fancy Indexing in 2-D :",a)

Fancy Indexing in 2-D : [ 1 12 23 34 45]


In [7]:
#fancy indexing in 2-D
arr=np.array([[0,1,2,3,4,5],
            [10,11,12,13,14,15],
            [20,21,22,23,24,25],
            [30,31,32,33,34,35],
            [40,41,42,43,44,45],
            [50,51,52,53,54,55]])
print("Normal array :\n",arr) 
a=arr[3:,[0, 2, 5]]
print("After Indexing :\n",a)

Normal array :
 [[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
After Indexing :
 [[30 32 35]
 [40 42 45]
 [50 52 55]]


In [8]:
arr=np.array([[0,1,2,3,4,5],
            [10,11,12,13,14,15],
            [20,21,22,23,24,25],
            [30,31,32,33,34,35],
            [40,41,42,43,44,45],
            [50,51,52,53,54,55]])
mask = np.array([1,0,1,0,0,1],dtype=bool) 
#mask with column 2 
b=arr[mask,2]
print("After masking :\n")
print(b)

After masking :

[ 2 22 52]


In [12]:
arr=[[1],[2],[3]]
arr1=[1,2,3]
print(arr)
print(arr1)
if arr==arr1:
    print("Ok Bye!")
else:
    print("Let's just stay!")

[[1], [2], [3]]
[1, 2, 3]
Let's just stay!


In [26]:
#Fancy Indexing
import numpy as np
from numpy import *

arr=arange(0,80,10)
print("arr:",arr)
y=take(arr,[1,2,-3])
print("\ny:",y)

arr: [ 0 10 20 30 40 50 60 70]

y: [10 20 50]


In [37]:
#Fancy Indexing
 #Compress Function
arr1=array([[0,1,2,3,4,5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])
mask=array([1,0,1,0,0,1],dtype=bool)    #The concept of mask works for only 0's and 1's
#This produces output for 1st row
mask1=array([1,0,1],dtype=bool)
b=compress(mask,arr1)
c=compress(mask1,arr1)
print("b:",b)
print("c:",c)

b: [0 2 5]
c: [0 2]


In [53]:
#Modifying values with Fancy Indexing
x=np.array([0,1,2,3,4,5,6,7,8,9])
i=np.array([2,1,8,4])
print("x:",x)
print("i:",i)
print("x[i] :",x[i])
x[i]=99   #Here array is passed to an array
print("Updated x[i] :",x[i])
print("x:",x)

x: [0 1 2 3 4 5 6 7 8 9]
i: [2 1 8 4]
x[i] : [2 1 8 4]
Updated x[i] : [99 99 99 99]
x: [ 0 99 99  3 99  5  6  7 99  9]


In [48]:
#Clip
a=array([[1,2,3],[4,5,6]])
b=a.clip(3,5)
#set value less than 3 equal to 3
#set value greater than 5 equal to 5
print("b:\n",b)

b:
 [[3 3 3]
 [4 5 5]]


In [64]:
#Dot Product
x=np.array([2,4])
y=np.array([1,3])

#Method 1:
dot_product=0
print("zip(x,y) :",list(zip(x,y)))
for a,b in zip(x,y):
    print("a:",a)
    print("b:",b)
    dot_product+=a*b     #(2*1 + 4*3)
print(dot_product)

#Method 2:
a=x*y      #product of two arrays
print("a:",a)
print(a.sum())

#Method 3:
print(x.dot(y))

zip(x,y) : [(2, 1), (4, 3)]
a: 2
b: 1
a: 4
b: 3
14
a: [ 2 12]
14
14


In [87]:
#Methods to concatenate two arrays.
#Method 1:Using concatenate() function
a = np.array([[1, 2], [3, 4]])   # 2x2
b = np.array([[5, 6],[7,8]])     # 1x2
print("a:\n",a)
print("b:\n",b)

c=concatenate((a,b),axis=0)
r=concatenate((a,b),axis=1)
cr=concatenate((a,b),axis=None)

print("Column(c) Concatenation:\n",c)  #axis=0 means Column
print("Row(r) Concatenation:\n",r)     #axis=1 means Row
print("Concatenation:\n",cr)
print("r.size :",r.size)
print("r.dtype :",r.dtype)
print("c.size :",c.size)

a:
 [[1 2]
 [3 4]]
b:
 [[5 6]
 [7 8]]
Column(c) Concatenation:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Row(r) Concatenation:
 [[1 2 5 6]
 [3 4 7 8]]
Concatenation:
 [1 2 3 4 5 6 7 8]
r.size : 8
r.dtype : int32
c.size : 8


In [98]:
#concatenation() function(part 2)
a=np.array([[1,2],[3,4]])
b=np.array([[5, 6]])
print("Column Concatenation:\n",np.concatenate((a,b),axis=0))

#print("Row Concatenation:\n",np.concatenate((a,b),axis=1)) 
# ValueError: all the input array dimensions except for the concatenation axis must match exactly
print("Row Concatenation:\n",np.concatenate((a, b.T), axis=1))

print("Concatenation:\n",np.concatenate((a,b),axis=None))

Column Concatenation:
 [[1 2]
 [3 4]
 [5 6]]
Row Concatenation:
 [[1 2 5]
 [3 4 6]]
Concatenation:
 [1 2 3 4 5 6]


In [104]:
#Method 2: numpy.vstack
#It stack arrays in sequence vertically(row-wise)
a=np.array([1, 2, 3])
b=np.array([2, 3, 4])
res=np.vstack((a,b))
print("res:\n",res)

a=np.array([[1],[2],[3]])
print("a:\n",a)
b=np.array([[2],[3],[4]])
res1=np.vstack((a,b))
print("res1:\n",res1)

res:
 [[1 2 3]
 [2 3 4]]
a:
 [[1]
 [2]
 [3]]
res1:
 [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [106]:
#Method 3: numpy.hstack
#It stack arrays in sequence horizontally(column-wise)
a = np.array((1,2,3))
b = np.array((4,5,6))
print("res:\n",np.hstack((a,b)))

a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
print("res1:\n",np.hstack((a,b)))

res:
 [1 2 3 4 5 6]
res1:
 [[1 4]
 [2 5]
 [3 6]]


In [112]:
#tile() : It constructs an array by repeating 'A' the number of times given by reps.
a=np.array([0,1,2])
print("1:\n",np.tile(a,2))
print("2:\n",np.tile(a,(2,2)))
print("3:\n",np.tile(a,(2,1,2))) #row=1 ,col=2

1:
 [0 1 2 0 1 2]
2:
 [[0 1 2 0 1 2]
 [0 1 2 0 1 2]]
3:
 [[[0 1 2 0 1 2]]

 [[0 1 2 0 1 2]]]


In [121]:
# Python code to demonstrate the working of zip() 

# initializing lists 
name = [ "Manjeet", "Nikhil", "Shambhavi", "Astha" ] 
roll_no = [ 4, 1, 3, 2 ] 
marks = [ 40, 50, 60, 70 ] 

# using zip() to map values 
mapped = zip(name, roll_no, marks) 

# converting values to print as set 
mapped = list(mapped) 

# printing resultant values 
print ("The zipped result is : ",end="") 
print (mapped) 

# unzipping values 
namz, roll_noz, marksz = zip(*mapped) 

print ("The unzipped result: \n",end="") 

# printing initial lists 
print ("The name list is : ",end="") 
print (namz) 

print ("The roll_no list is : ",end="") 
print (roll_noz) 

print ("The marks list is : ",end="") 
print (marksz)

The zipped result is : [('Manjeet', 4, 40), ('Nikhil', 1, 50), ('Shambhavi', 3, 60), ('Astha', 2, 70)]
The unzipped result: 
The name list is : ('Manjeet', 'Nikhil', 'Shambhavi', 'Astha')
The roll_no list is : (4, 1, 3, 2)
The marks list is : (40, 50, 60, 70)


In [130]:
# Python program to demonstrate the use of index arrays.
import numpy as np
 
# Create a sequence of integers from 10 to 1 with a step of -2
a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a)
 
# Indexes are specified inside the np.array method.
newarr = a[[3, 1, 2 ]]
print("\n Elements at these indices are:\n",newarr)
print(a)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]
[10  8  6  4  2]


In [131]:
# Python program showing advanced indexing
import numpy as np
 
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

[1 3 6]


In [134]:
#WAP:To square the multiples of 40 
import numpy as np
 
a = np.array([10, 40, 80, 50, 100])
print(a[10%40==0]**2)
print(a[a%40==0]**2)

[]
[1600 6400]


In [138]:
#To add the vector 'v' to each row of the matrix 'x' and store the result in matrix 'y'.
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)  
for i in range(4):
    y[i, :] = x[i, :] + v
print("y:",y)

y: [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [143]:
arr=np.array([[[0, 1, 2, 0, 1, 2]],
       [[0, 1, 2, 0, 1, 2]]])
print("arr:",arr)
print(arr.ndim)
print(arr.size)
rows=len(arr)
cols=len(arr[0])
print("rows:",rows)
print("cols:",cols)
#(row,col)-> (2,1)

arr: [[[0 1 2 0 1 2]]

 [[0 1 2 0 1 2]]]
3
12
rows: 2
cols: 1


In [156]:
a=np.array([0,1,2])
ar=np.tile(a,(2, 1, 2))
print("dimensions:",ar.ndim)
rows=len(ar)
print("rows:",rows)
cols=len(arr[0])
print("cols:",cols)
print("ar:",ar)
print("shape of ar:",ar.shape)
#d=2   reps
#ar.ndim=3
#ar.ndim > d
#So, reps(d) is promoted to ar.ndim by pre-pending 1’s to it.

dimensions: 3
rows: 2
cols: 1
ar: [[[0 1 2 0 1 2]]

 [[0 1 2 0 1 2]]]
shape of ar: (2, 1, 6)


In [161]:
#tile()
import numpy as geek
arr = geek.arange(4).reshape(2,2)
print(arr)  #array is 2-d
print(arr.ndim)
print("\nRepeating arr : \n", geek.tile(arr, 1)) 

#repetition=1
#arr.ndim=2
#arr.ndim < reps
#If arr.ndim > repetitions, reps is promoted to arr.ndim by pre-pending 1’s to it.
#If arr.ndim < repetitions, reps is promoted to arr.ndim by pre-pending new axis.

[[0 1]
 [2 3]]
2

Repeating arr : 
 [[0 1]
 [2 3]]


In [169]:
arr = geek.arange(4)
print(arr.shape)
print(arr)
print("\nRepeating arr : \n", geek.tile(arr,2))
#promoted to (1,4)

(4,)
[0 1 2 3]

Repeating arr : 
 [0 1 2 3 0 1 2 3]


In [172]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y = x + v         #Add v to each row of x using broadcasting
print("y:\n",y)

y:
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [213]:
#Broadcasting
a = array( (0,10,20,30) )
b = array( (0,1,2) )
print(" a:" , a)
print(" b:" , b)
#print(a+b)
print("a[:,None] :\n",a[:,None]) 
y = a[:,None] + b
#print(a[:,None].shape)
print("y:\n",y)
print("a[None,:] :",a[None,:])

 a: [ 0 10 20 30]
 b: [0 1 2]
a[:,None] :
 [[ 0]
 [10]
 [20]
 [30]]
y:
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
a[None,:] : [[ 0 10 20 30]]


In [192]:
macros = array([ 
[0.8, 2.9, 3.9], 
[52.4, 23.6, 36.5], 
[55.2, 31.7, 23.9], 
[14.4, 11, 4.9] 
]) 

# Create a new array filled with zeros, 
# of the same shape as macros. 
result = zeros_like(macros) 
print(result)
cal_per_macro = array([3, 3, 8]) 
print(cal_per_macro)

#Now multiply each row of macros by cal_per_macro.In Numpy,`*` is element-wise multiplication between two arrays. 
#print(macros.shape[0])
#print(len(macros))
3
for i in range(len(macros)): 
	result[i, :] = macros[i, :]*cal_per_macro 
print("\n",result)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 3 8]

 [[  2.4   8.7  31.2]
 [157.2  70.8 292. ]
 [165.6  95.1 191.2]
 [ 43.2  33.   39.2]]


In [2]:
import numpy as np
type(np.int_(10))

numpy.int32

In [5]:
print(int is np.int_)
print(int is np.int)

False
True
